// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../counterfact-types/index.ts";
import type { issue } from "../../../../../../../../components/schemas/issue.js";
import type { moved_permanently } from "../../../../../../../../#/components/responses/moved_permanently.js";
import type { bad_request } from "../../../../../../../../#/components/responses/bad_request.js";
import type { requires_authentication } from "../../../../../../../../#/components/responses/requires_authentication.js";
import type { forbidden } from "../../../../../../../../#/components/responses/forbidden.js";
import type { not_found } from "../../../../../../../../#/components/responses/not_found.js";
import type { gone } from "../../../../../../../../#/components/responses/gone.js";

/**
 * You can use the REST API to remove a dependency that an issue is blocked by.
 *
 * Removing content too quickly using this endpoint may result in secondary rate limiting.
 * For more information, see [Rate limits for the API](https://docs.github.com/rest/using-the-rest-api/rate-limits-for-the-rest-api#about-secondary-rate-limits)
 * and [Best practices for using the REST API](https://docs.github.com/rest/guides/best-practices-for-using-the-rest-api).
 *
 * This endpoint supports the following custom media types. For more information, see [Media types](https://docs.github.com/rest/using-the-rest-api/getting-started-with-the-rest-api#media-types).
 * - **`application/vnd.github.raw+json`**: Returns the raw Markdown body. Response will include `body`. This is the default if you do not pass a specific media type.
 * - **`application/vnd.github.text+json`**: Returns a text only representation of the Markdown body. Response will include `body_text`.
 * - **`application/vnd.github.html+json`**: Returns HTML rendered from the body's Markdown. Response will include `body_html`.
 * - **`application/vnd.github.full+json`**: Returns raw, text, and HTML representations. Response will include `body`, `body_text`, and `body_html`.
 */
export type issuesRemoveDependencyBlockedBy = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: issuesRemoveDependencyBlockedBy_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: issue;
          };
        };
        examples: {
          default: unknown;
        };
      };
      301: moved_permanently;
      400: bad_request;
      401: requires_authentication;
      403: forbidden;
      404: not_found;
      410: gone;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type issuesRemoveDependencyBlockedBy_Path = {
  owner: string;
  repo: string;
  issue_number: number;
  /**
   * The id of the blocking issue to remove as a dependency
   */
  issue_id: number;
};
