// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../../counterfact-types/index.ts";
import type { job } from "../../../../../../../../../components/schemas/job.js";
import type { not_found } from "../../../../../../../../../#/components/responses/not_found.js";

/**
 * Lists jobs for a specific workflow run attempt. You can use parameters to narrow the list of results. For more information
 * about using parameters, see [Parameters](https://docs.github.com/rest/guides/getting-started-with-the-rest-api#parameters).
 *
 * Anyone with read access to the repository can use this endpoint.
 *
 * OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint  with a private repository.
 */
export type actionsListJobsForWorkflowRunAttempt = (
  $: OmitValueWhenNever<{
    query: actionsListJobsForWorkflowRunAttempt_Query;
    querystring: never;
    path: actionsListJobsForWorkflowRunAttempt_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: { total_count: number; jobs: Array<job> };
          };
        };
        examples: {
          default: unknown;
        };
      };
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type actionsListJobsForWorkflowRunAttempt_Query = {
  per_page?: number;
  page?: number;
};

export type actionsListJobsForWorkflowRunAttempt_Path = {
  owner: string;
  repo: string;
  run_id: number;
  attempt_number: number;
};
