// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { ExpiringTargetGetResponse } from "../../../../../../../components/schemas/ExpiringTargetGetResponse.js";
import type { UnauthorizedErrorRep } from "../../../../../../../components/schemas/UnauthorizedErrorRep.js";
import type { ForbiddenErrorRep } from "../../../../../../../components/schemas/ForbiddenErrorRep.js";
import type { NotFoundErrorRep } from "../../../../../../../components/schemas/NotFoundErrorRep.js";
import type { RateLimitedErrorRep } from "../../../../../../../components/schemas/RateLimitedErrorRep.js";
import type { patchFlagsRequest } from "../../../../../../../components/schemas/patchFlagsRequest.js";
import type { ExpiringTargetPatchResponse } from "../../../../../../../components/schemas/ExpiringTargetPatchResponse.js";
import type { InvalidRequestErrorRep } from "../../../../../../../components/schemas/InvalidRequestErrorRep.js";

/**
 * Get a list of context targets on a feature flag that are scheduled for removal.
 */
export type getExpiringContextTargets = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: getExpiringContextTargets_Path;
    headers: getExpiringContextTargets_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ExpiringTargetGetResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Schedule a context for removal from individual targeting on a feature flag. The flag must already individually target the context.
 *
 * You can add, update, or remove a scheduled removal date. You can only schedule a context for removal on a single variation per flag.
 *
 * Updating an expiring target uses the semantic patch format. To make a semantic patch request, you must append `domain-model=launchdarkly.semanticpatch` to your `Content-Type` header. To learn more, read [Updates using semantic patch](/reference#updates-using-semantic-patch).
 *
 * ### Instructions
 *
 * Semantic patch requests support the following `kind` instructions for updating expiring targets.
 *
 * <details>
 * <summary>Click to expand instructions for <strong>updating expiring targets</strong></summary>
 *
 * #### addExpiringTarget
 *
 * Adds a date and time that LaunchDarkly will remove the context from the flag's individual targeting.
 *
 * ##### Parameters
 *
 * * `value`: The time, in Unix milliseconds, when LaunchDarkly should remove the context from individual targeting for this flag
 * * `variationId`: ID of a variation on the flag
 * * `contextKey`: The context key for the context to remove from individual targeting
 * * `contextKind`: The kind of context represented by the `contextKey`
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "addExpiringTarget",
 *     "value": 1754006460000,
 *     "variationId": "4254742c-71ae-411f-a992-43b18a51afe0",
 *     "contextKey": "user-key-123abc",
 *     "contextKind": "user"
 *   }]
 * }
 * ```
 *
 * #### updateExpiringTarget
 *
 * Updates the date and time that LaunchDarkly will remove the context from the flag's individual targeting
 *
 * ##### Parameters
 *
 * * `value`: The time, in Unix milliseconds, when LaunchDarkly should remove the context from individual targeting for this flag
 * * `variationId`: ID of a variation on the flag
 * * `contextKey`: The context key for the context to remove from individual targeting
 * * `contextKind`: The kind of context represented by the `contextKey`
 * * `version`: (Optional) The version of the expiring target to update. If included, update will fail if version doesn't match current version of the expiring target.
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "updateExpiringTarget",
 *     "value": 1754006460000,
 *     "variationId": "4254742c-71ae-411f-a992-43b18a51afe0",
 *     "contextKey": "user-key-123abc",
 *     "contextKind": "user"
 *   }]
 * }
 * ```
 *
 * #### removeExpiringTarget
 *
 * Removes the scheduled removal of the context from the flag's individual targeting. The context will remain part of the flag's individual targeting until you explicitly remove it, or until you schedule another removal.
 *
 * ##### Parameters
 *
 * * `variationId`: ID of a variation on the flag
 * * `contextKey`: The context key for the context to remove from individual targeting
 * * `contextKind`: The kind of context represented by the `contextKey`
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "removeExpiringTarget",
 *     "variationId": "4254742c-71ae-411f-a992-43b18a51afe0",
 *     "contextKey": "user-key-123abc",
 *     "contextKind": "user"
 *   }]
 * }
 * ```
 *
 * </details>
 *
 */
export type patchExpiringTargets = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: patchExpiringTargets_Path;
    headers: patchExpiringTargets_Headers;
    cookie: never;
    body: patchFlagsRequest;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ExpiringTargetPatchResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InvalidRequestErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type getExpiringContextTargets_Path = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The feature flag key
   */
  featureFlagKey: string;
};

export type getExpiringContextTargets_Headers = { Authorization: string };

export type patchExpiringTargets_Path = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The feature flag key
   */
  featureFlagKey: string;
};

export type patchExpiringTargets_Headers = { Authorization: string };
