// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../counterfact-types/index.ts";
import type { Context } from "../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../counterfact-types/index.ts";
import type { codespace } from "../../../components/schemas/codespace.js";
import type { not_modified } from "../../../#/components/responses/not_modified.js";
import type { requires_authentication } from "../../../#/components/responses/requires_authentication.js";
import type { forbidden } from "../../../#/components/responses/forbidden.js";
import type { not_found } from "../../../#/components/responses/not_found.js";
import type { internal_error } from "../../../#/components/responses/internal_error.js";

/**
 * Lists the codespaces associated to a specified organization.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint.
 */
export type codespacesListInOrganization = (
  $: OmitValueWhenNever<{
    query: codespacesListInOrganization_Query;
    querystring: never;
    path: codespacesListInOrganization_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: { total_count: number; codespaces: Array<codespace> };
          };
        };
        examples: {
          default: unknown;
        };
      };
      304: not_modified;
      401: requires_authentication;
      403: forbidden;
      404: not_found;
      500: internal_error;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type codespacesListInOrganization_Query = {
  per_page?: number;
  page?: number;
};

export type codespacesListInOrganization_Path = { org: string };
