// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../counterfact-types/index.ts";
import type { Context } from "../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../counterfact-types/index.ts";
import type { repository_advisory } from "../../../components/schemas/repository-advisory.js";
import type { bad_request } from "../../../#/components/responses/bad_request.js";
import type { not_found } from "../../../#/components/responses/not_found.js";

/**
 * Lists repository security advisories for an organization.
 *
 * The authenticated user must be an owner or security manager for the organization to use this endpoint.
 *
 * OAuth app tokens and personal access tokens (classic) need the `repo` or `repository_advisories:write` scope to use this endpoint.
 */
export type securityAdvisoriesListOrgRepositoryAdvisories = (
  $: OmitValueWhenNever<{
    query: securityAdvisoriesListOrgRepositoryAdvisories_Query;
    querystring: never;
    path: securityAdvisoriesListOrgRepositoryAdvisories_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<repository_advisory>;
          };
        };
        examples: {
          default: unknown;
        };
      };
      400: bad_request;
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type securityAdvisoriesListOrgRepositoryAdvisories_Query = {
  direction?: "asc" | "desc";
  /**
   * The property to sort the results by.
   */
  sort?: "created" | "updated" | "published";
  before?: string;
  after?: string;
  /**
   * The number of advisories to return per page. For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."
   */
  per_page?: number;
  /**
   * Filter by the state of the repository advisories. Only advisories of this state will be returned.
   */
  state?: "triage" | "draft" | "published" | "closed";
};

export type securityAdvisoriesListOrgRepositoryAdvisories_Path = {
  org: string;
};
