// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../counterfact-types/index.ts";
import type { Context } from "../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../counterfact-types/index.ts";
import type { team } from "../../../components/schemas/team.js";
import type { forbidden } from "../../../#/components/responses/forbidden.js";
import type { team_full } from "../../../components/schemas/team-full.js";
import type { validation_failed } from "../../../#/components/responses/validation_failed.js";

/**
 * Lists all teams in an organization that are visible to the authenticated user.
 */
export type teamsList = (
  $: OmitValueWhenNever<{
    query: teamsList_Query;
    querystring: never;
    path: teamsList_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<team>;
          };
        };
        examples: {
          default: unknown;
        };
      };
      403: forbidden;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * To create a team, the authenticated user must be a member or owner of `{org}`. By default, organization members can create teams. Organization owners can limit team creation to organization owners. For more information, see "[Setting team creation permissions](https://docs.github.com/articles/setting-team-creation-permissions-in-your-organization)."
 *
 * When you create a new team, you automatically become a team maintainer without explicitly adding yourself to the optional array of `maintainers`. For more information, see "[About teams](https://docs.github.com/github/setting-up-and-managing-organizations-and-teams/about-teams)".
 */
export type teamsCreate = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: teamsCreate_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * The name of the team.
       */
      name: string;
      /**
       * The description of the team.
       */
      description?: string;
      /**
       * List GitHub usernames for organization members who will become team maintainers.
       */
      maintainers?: Array<string>;
      /**
       * The full name (e.g., "organization-name/repository-name") of repositories to add the team to.
       */
      repo_names?: Array<string>;
      /**
       * The level of privacy this team should have. The options are:
       * **For a non-nested team:**
       *  * `secret` - only visible to organization owners and members of this team.
       *  * `closed` - visible to all members of this organization.
       * Default: `secret`
       * **For a parent or child team:**
       *  * `closed` - visible to all members of this organization.
       * Default for child team: `closed`
       */
      privacy?: "secret" | "closed";
      /**
       * The notification setting the team has chosen. The options are:
       *  * `notifications_enabled` - team members receive notifications when the team is @mentioned.
       *  * `notifications_disabled` - no one receives notifications.
       * Default: `notifications_enabled`
       */
      notification_setting?: "notifications_enabled" | "notifications_disabled";
      /**
       * **Closing down notice**. The permission that new repositories will be added to the team with when none is specified.
       * @default "pull"
       */
      permission?: "pull" | "push";
      /**
       * The ID of a team to set as the parent team.
       */
      parent_team_id?: number;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: team_full;
          };
        };
        examples: {
          default: unknown;
        };
      };
      403: forbidden;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type teamsList_Query = {
  per_page?: number;
  page?: number;
  team_type?: "all" | "enterprise" | "organization";
};

export type teamsList_Path = { org: string };

export type teamsCreate_Path = { org: string };
