// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../counterfact-types/index.ts";
import type { MaybePromise } from "../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../counterfact-types/index.ts";
import type { Context } from "../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../counterfact-types/index.ts";
import type { base_gist } from "../components/schemas/base-gist.js";
import type { not_modified } from "../#/components/responses/not_modified.js";
import type { forbidden } from "../#/components/responses/forbidden.js";
import type { gist_simple } from "../components/schemas/gist-simple.js";
import type { not_found } from "../#/components/responses/not_found.js";
import type { validation_failed } from "../#/components/responses/validation_failed.js";

/**
 * Lists the authenticated user's gists or if called anonymously, this endpoint returns all public gists:
 */
export type gistsList = (
  $: OmitValueWhenNever<{
    query: gistsList_Query;
    querystring: never;
    path: never;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<base_gist>;
          };
        };
        examples: {
          default: unknown;
        };
      };
      304: not_modified;
      403: forbidden;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Allows you to add a new gist with one or more files.
 *
 * > [!NOTE]
 * > Don't name your files "gistfile" with a numerical suffix. This is the format of the automatic naming scheme that Gist uses internally.
 */
export type gistsCreate = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: never;
    headers: never;
    cookie: never;
    body: {
      /**
       * Description of the gist
       * @example "Example Ruby script"
       */
      description?: string;
      /**
       * Names and content for the files that make up the gist
       * @example {"hello.rb":{"content":"puts \"Hello, World!\""}}
       */
      files: {
        [key: string]: {
          /**
           * Content of the file
           */
          content: string;
        };
      };
      public?: boolean | "true" | "false";
    };
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: {
          Location: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: gist_simple;
          };
        };
        examples: {
          default: unknown;
        };
      };
      304: not_modified;
      403: forbidden;
      404: not_found;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type gistsList_Query = {
  since?: string;
  per_page?: number;
  page?: number;
};
