// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../counterfact-types/index.ts";
import type { MaybePromise } from "../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../counterfact-types/index.ts";
import type { Context } from "../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../counterfact-types/index.ts";
import type { not_modified } from "../#/components/responses/not_modified.js";

/**
 * Depending on what is rendered in the Markdown, you may need to provide additional token scopes for labels, such as `issues:read` or `pull_requests:read`.
 */
export type markdownRender = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: never;
    headers: never;
    cookie: never;
    body: {
      /**
       * The Markdown text to render in HTML.
       */
      text: string;
      /**
       * The rendering mode.
       * @default "markdown"
       * @example "markdown"
       */
      mode?: "markdown" | "gfm";
      /**
       * The repository context to use when creating references in `gfm` mode.  For example, setting `context` to `octo-org/octo-repo` will change the text `#42` into an HTML link to issue 42 in the `octo-org/octo-repo` repository.
       */
      context?: string;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          "Content-Type": { schema: string };
          "Content-Length": { schema: string };
          "X-CommonMarker-Version": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "text/html": {
            schema: string;
          };
        };
        examples: {
          default: unknown;
        };
      };
      304: not_modified;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;
