// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../counterfact-types/index.ts";
import type { MaybePromise } from "../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../counterfact-types/index.ts";
import type { Context } from "../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../counterfact-types/index.ts";
import type { private_user } from "../components/schemas/private-user.js";
import type { public_user } from "../components/schemas/public-user.js";
import type { not_modified } from "../#/components/responses/not_modified.js";
import type { requires_authentication } from "../#/components/responses/requires_authentication.js";
import type { forbidden } from "../#/components/responses/forbidden.js";
import type { not_found } from "../#/components/responses/not_found.js";
import type { validation_failed } from "../#/components/responses/validation_failed.js";

/**
 * OAuth app tokens and personal access tokens (classic) need the `user` scope in order for the response to include private profile information.
 */
export type usersGetAuthenticated = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: never;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: private_user | public_user;
          };
        };
        examples: {
          "response-with-public-and-private-profile-information": unknown;
          "response-with-public-profile-information": unknown;
        };
      };
      304: not_modified;
      401: requires_authentication;
      403: forbidden;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * **Note:** If your email is set to private and you send an `email` parameter as part of this request to update your profile, your privacy settings are still enforced: the email address will not be displayed on your public profile or via the API.
 */
export type usersUpdateAuthenticated = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: never;
    headers: never;
    cookie: never;
    body: {
      /**
       * The new name of the user.
       * @example "Omar Jahandar"
       */
      name?: string;
      /**
       * The publicly visible email address of the user.
       * @example "omar@example.com"
       */
      email?: string;
      /**
       * The new blog URL of the user.
       * @example "blog.example.com"
       */
      blog?: string;
      /**
       * The new Twitter username of the user.
       * @example "therealomarj"
       */
      twitter_username?: string;
      /**
       * The new company of the user.
       * @example "Acme corporation"
       */
      company?: string;
      /**
       * The new location of the user.
       * @example "Berlin, Germany"
       */
      location?: string;
      /**
       * The new hiring availability of the user.
       */
      hireable?: boolean;
      /**
       * The new short biography of the user.
       */
      bio?: string;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: private_user;
          };
        };
        examples: {
          default: unknown;
        };
      };
      304: not_modified;
      401: requires_authentication;
      403: forbidden;
      404: not_found;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;
