// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { InsightsChart } from "../../../../../../components/schemas/InsightsChart.js";
import type { ValidationFailedErrorRep } from "../../../../../../components/schemas/ValidationFailedErrorRep.js";
import type { UnauthorizedErrorRep } from "../../../../../../components/schemas/UnauthorizedErrorRep.js";
import type { ForbiddenErrorRep } from "../../../../../../components/schemas/ForbiddenErrorRep.js";
import type { NotFoundErrorRep } from "../../../../../../components/schemas/NotFoundErrorRep.js";
import type { RateLimitedErrorRep } from "../../../../../../components/schemas/RateLimitedErrorRep.js";

/**
 * Get stale flags chart data. Engineering insights displays stale flags data in the [flag health metric view](https://docs.launchdarkly.com/home/engineering-insights/metrics/flag-health).
 *
 * ### Expanding the chart response
 *
 * LaunchDarkly supports expanding the chart response to include additional fields.
 *
 * To expand the response, append the `expand` query parameter and include the following:
 *
 * * `metrics` includes details on the metrics related to stale flags
 *
 * For example, use `?expand=metrics` to include the `metrics` field in the response. By default, this field is **not** included in the response.
 *
 */
export type getStaleFlagsChart = (
  $: OmitValueWhenNever<{
    query: getStaleFlagsChart_Query;
    querystring: never;
    path: never;
    headers: getStaleFlagsChart_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InsightsChart;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ValidationFailedErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type getStaleFlagsChart_Query = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * Comma separated list of application keys
   */
  applicationKey?: string;
  /**
   * Property to group results by. Options: `maintainer`
   */
  groupBy?: string;
  /**
   * Comma-separated list of individual maintainers to filter results.
   */
  maintainerId?: string;
  /**
   * Comma-separated list of team maintainer keys to filter results.
   */
  maintainerTeamKey?: string;
  /**
   * Options: `metrics`
   */
  expand?: string;
};

export type getStaleFlagsChart_Headers = { Authorization: string };
