// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { rule_suites } from "../../../../../components/schemas/rule-suites.js";
import type { not_found } from "../../../../../#/components/responses/not_found.js";
import type { internal_error } from "../../../../../#/components/responses/internal_error.js";

/**
 * Lists suites of rule evaluations at the repository level.
 * For more information, see "[Managing rulesets for a repository](https://docs.github.com/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/managing-rulesets-for-a-repository#viewing-insights-for-rulesets)."
 */
export type reposGetRepoRuleSuites = (
  $: OmitValueWhenNever<{
    query: reposGetRepoRuleSuites_Query;
    querystring: never;
    path: reposGetRepoRuleSuites_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: rule_suites;
          };
        };
        examples: {
          default: unknown;
        };
      };
      404: not_found;
      500: internal_error;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type reposGetRepoRuleSuites_Query = {
  ref?: string;
  time_period?: "hour" | "day" | "week" | "month";
  actor_name?: string;
  rule_suite_result?: "pass" | "fail" | "bypass" | "all";
  per_page?: number;
  page?: number;
};

export type reposGetRepoRuleSuites_Path = { owner: string; repo: string };
