// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { empty_object } from "../../../../../../../components/schemas/empty-object.js";
import type { forbidden } from "../../../../../../../#/components/responses/forbidden.js";
import type { not_found } from "../../../../../../../#/components/responses/not_found.js";

/**
 * Approves a workflow run for a pull request from a public fork of a first time contributor. For more information, see ["Approving workflow runs from public forks](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)."
 *
 * OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
 */
export type actionsApproveWorkflowRun = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: actionsApproveWorkflowRun_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: empty_object;
          };
        };
        examples: {
          default: unknown;
        };
      };
      403: forbidden;
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type actionsApproveWorkflowRun_Path = {
  owner: string;
  repo: string;
  run_id: number;
};
