// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { forbidden } from "../../../../../../../#/components/responses/forbidden.js";
import type { internal_error } from "../../../../../../../#/components/responses/internal_error.js";

/**
 * Gets a redirect URL to download an archive of log files for a workflow run. This link expires after 1 minute. Look for
 * `Location:` in the response header to find the URL for the download.
 *
 * Anyone with read access to the repository can use this endpoint.
 *
 * If the repository is private, OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
 */
export type actionsDownloadWorkflowRunLogs = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: actionsDownloadWorkflowRunLogs_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      302: {
        headers: {
          Location: { schema: string };
        };
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Deletes all logs for a workflow run.
 *
 * OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
 */
export type actionsDeleteWorkflowRunLogs = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: actionsDeleteWorkflowRunLogs_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      403: forbidden;
      500: internal_error;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type actionsDownloadWorkflowRunLogs_Path = {
  owner: string;
  repo: string;
  run_id: number;
};

export type actionsDeleteWorkflowRunLogs_Path = {
  owner: string;
  repo: string;
  run_id: number;
};
