// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { repository } from "../../../../../../components/schemas/repository.js";
import type { forbidden } from "../../../../../../#/components/responses/forbidden.js";
import type { not_found } from "../../../../../../#/components/responses/not_found.js";
import type { validation_failed } from "../../../../../../#/components/responses/validation_failed.js";

/**
 * Lists repositories that are allowed to use self-hosted runners in an organization.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope or the "Actions policies" fine-grained permission to use this endpoint.
 */
export type actionsListSelectedRepositoriesSelfHostedRunnersOrganization = (
  $: OmitValueWhenNever<{
    query: actionsListSelectedRepositoriesSelfHostedRunnersOrganization_Query;
    querystring: never;
    path: actionsListSelectedRepositoriesSelfHostedRunnersOrganization_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: { total_count?: number; repositories?: Array<repository> };
          };
        };
        examples: {
          default: unknown;
        };
      };
      403: forbidden;
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Sets repositories that are allowed to use self-hosted runners in an organization.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope or the "Actions policies" fine-grained permission to use this endpoint.
 */
export type actionsSetSelectedRepositoriesSelfHostedRunnersOrganization = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: actionsSetSelectedRepositoriesSelfHostedRunnersOrganization_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * IDs of repositories that can use repository-level self-hosted runners
       */
      selected_repository_ids: Array<number>;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      403: forbidden;
      404: not_found;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type actionsListSelectedRepositoriesSelfHostedRunnersOrganization_Query =
  { per_page?: number; page?: number };

export type actionsListSelectedRepositoriesSelfHostedRunnersOrganization_Path =
  { org: string };

export type actionsSetSelectedRepositoriesSelfHostedRunnersOrganization_Path = {
  org: string;
};
