// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../counterfact-types/index.ts";
import type { ExtinctionListPost } from "../../../../../../../../components/schemas/ExtinctionListPost.js";
import type { InvalidRequestErrorRep } from "../../../../../../../../components/schemas/InvalidRequestErrorRep.js";
import type { UnauthorizedErrorRep } from "../../../../../../../../components/schemas/UnauthorizedErrorRep.js";
import type { ForbiddenErrorRep } from "../../../../../../../../components/schemas/ForbiddenErrorRep.js";
import type { NotFoundErrorRep } from "../../../../../../../../components/schemas/NotFoundErrorRep.js";
import type { RateLimitedErrorRep } from "../../../../../../../../components/schemas/RateLimitedErrorRep.js";

/**
 * Create a new extinction.
 */
export type postExtinction = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: postExtinction_Path;
    headers: postExtinction_Headers;
    cookie: never;
    body: ExtinctionListPost;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InvalidRequestErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type postExtinction_Path = {
  /**
   * The repository name
   */
  repo: string;
  /**
   * The URL-encoded branch name
   */
  branch: string;
};

export type postExtinction_Headers = { Authorization: string };
