// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../counterfact-types/index.ts";
import type { Context } from "../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../counterfact-types/index.ts";
import type { CustomRoles } from "../../../components/schemas/CustomRoles.js";
import type { UnauthorizedErrorRep } from "../../../components/schemas/UnauthorizedErrorRep.js";
import type { ForbiddenErrorRep } from "../../../components/schemas/ForbiddenErrorRep.js";
import type { RateLimitedErrorRep } from "../../../components/schemas/RateLimitedErrorRep.js";
import type { CustomRolePost } from "../../../components/schemas/CustomRolePost.js";
import type { CustomRole } from "../../../components/schemas/CustomRole.js";
import type { InvalidRequestErrorRep } from "../../../components/schemas/InvalidRequestErrorRep.js";
import type { StatusConflictErrorRep } from "../../../components/schemas/StatusConflictErrorRep.js";

/**
 * Get a complete list of custom roles. Custom roles let you create flexible policies providing fine-grained access control to everything in LaunchDarkly, from feature flags to goals, environments, and teams. With custom roles, it's possible to enforce access policies that meet your exact workflow needs. Custom roles are available to customers on our enterprise plans. If you're interested in learning more about our enterprise plans, contact sales@launchdarkly.com.
 */
export type getCustomRoles = (
  $: OmitValueWhenNever<{
    query: getCustomRoles_Query;
    querystring: never;
    path: never;
    headers: getCustomRoles_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: CustomRoles;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Create a new custom role
 */
export type postCustomRole = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: never;
    headers: postCustomRole_Headers;
    cookie: never;
    body: CustomRolePost;
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: CustomRole;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InvalidRequestErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      409: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: StatusConflictErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type getCustomRoles_Query = {
  /**
   * The maximum number of custom roles to return. Defaults to 20.
   */
  limit?: number;
  /**
   * Where to start in the list. Defaults to 0. Use this with pagination. For example, an offset of 10 skips the first ten items and then returns the next items in the list, up to the query `limit`.
   */
  offset?: number;
};

export type getCustomRoles_Headers = { Authorization: string };

export type postCustomRole_Headers = { Authorization: string };
