// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../counterfact-types/index.ts";
import type { Context } from "../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../counterfact-types/index.ts";
import type { team_full } from "../../components/schemas/team-full.js";
import type { not_found } from "../../#/components/responses/not_found.js";
import type { forbidden } from "../../#/components/responses/forbidden.js";
import type { validation_failed } from "../../#/components/responses/validation_failed.js";

/**
 * > [!WARNING]
 * > **Endpoint closing down notice:** This endpoint route is closing down and will be removed from the Teams API. We recommend migrating your existing code to use the [Get a team by name](https://docs.github.com/rest/teams/teams#get-a-team-by-name) endpoint.
 * @deprecated
 */
export type teamsGetLegacy = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: teamsGetLegacy_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: team_full;
          };
        };
        examples: {
          default: unknown;
        };
      };
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * > [!WARNING]
 * > **Endpoint closing down notice:** This endpoint route is closing down and will be removed from the Teams API. We recommend migrating your existing code to use the new [Update a team](https://docs.github.com/rest/teams/teams#update-a-team) endpoint.
 *
 * To edit a team, the authenticated user must either be an organization owner or a team maintainer.
 *
 * > [!NOTE]
 * > With nested teams, the `privacy` for parent teams cannot be `secret`.
 * @deprecated
 */
export type teamsUpdateLegacy = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: teamsUpdateLegacy_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * The name of the team.
       */
      name: string;
      /**
       * The description of the team.
       */
      description?: string;
      /**
       * The level of privacy this team should have. Editing teams without specifying this parameter leaves `privacy` intact. The options are:
       * **For a non-nested team:**
       *  * `secret` - only visible to organization owners and members of this team.
       *  * `closed` - visible to all members of this organization.
       * **For a parent or child team:**
       *  * `closed` - visible to all members of this organization.
       */
      privacy?: "secret" | "closed";
      /**
       * The notification setting the team has chosen. Editing teams without specifying this parameter leaves `notification_setting` intact. The options are:
       *  * `notifications_enabled` - team members receive notifications when the team is @mentioned.
       *  * `notifications_disabled` - no one receives notifications.
       */
      notification_setting?: "notifications_enabled" | "notifications_disabled";
      /**
       * **Closing down notice**. The permission that new repositories will be added to the team with when none is specified.
       * @default "pull"
       */
      permission?: "pull" | "push" | "admin";
      /**
       * The ID of a team to set as the parent team.
       */
      parent_team_id?: number;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: team_full;
          };
        };
        examples: {
          default: unknown;
        };
      };
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: team_full;
          };
        };
        examples: {
          default: unknown;
        };
      };
      403: forbidden;
      404: not_found;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * > [!WARNING]
 * > **Endpoint closing down notice:** This endpoint route is closing down and will be removed from the Teams API. We recommend migrating your existing code to use the new [Delete a team](https://docs.github.com/rest/teams/teams#delete-a-team) endpoint.
 *
 * To delete a team, the authenticated user must be an organization owner or team maintainer.
 *
 * If you are an organization owner, deleting a parent team will delete all of its child teams as well.
 * @deprecated
 */
export type teamsDeleteLegacy = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: teamsDeleteLegacy_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      404: not_found;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type teamsGetLegacy_Path = { team_id: number };

export type teamsUpdateLegacy_Path = { team_id: number };

export type teamsDeleteLegacy_Path = { team_id: number };
