// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { copilot_seat_details } from "../../../../../components/schemas/copilot-seat-details.js";
import type { requires_authentication } from "../../../../../#/components/responses/requires_authentication.js";
import type { forbidden } from "../../../../../#/components/responses/forbidden.js";
import type { not_found } from "../../../../../#/components/responses/not_found.js";
import type { internal_error } from "../../../../../#/components/responses/internal_error.js";

/**
 * > [!NOTE]
 * > This endpoint is in public preview and is subject to change.
 *
 * Lists all Copilot seats for which an organization with a Copilot Business or Copilot Enterprise subscription is currently being billed.
 * Only organization owners can view assigned seats.
 *
 * Each seat object contains information about the assigned user's most recent Copilot activity. Users must have telemetry enabled in their IDE for Copilot in the IDE activity to be reflected in `last_activity_at`.
 * For more information about activity data, see [Metrics data properties for GitHub Copilot](https://docs.github.com/copilot/reference/metrics-data).
 *
 * OAuth app tokens and personal access tokens (classic) need either the `manage_billing:copilot` or `read:org` scopes to use this endpoint.
 */
export type copilotListCopilotSeats = (
  $: OmitValueWhenNever<{
    query: copilotListCopilotSeats_Query;
    querystring: never;
    path: copilotListCopilotSeats_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              /**
               * Total number of Copilot seats for the organization currently being billed.
               */
              total_seats?: number;
              seats?: Array<copilot_seat_details>;
            };
          };
        };
        examples: {
          default: unknown;
        };
      };
      401: requires_authentication;
      403: forbidden;
      404: not_found;
      500: internal_error;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type copilotListCopilotSeats_Query = {
  page?: number;
  /**
   * The number of results per page (max 100). For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."
   */
  per_page?: number;
};

export type copilotListCopilotSeats_Path = { org: string };
