// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { ExpiringTargetGetResponse } from "../../../../../../../components/schemas/ExpiringTargetGetResponse.js";
import type { UnauthorizedErrorRep } from "../../../../../../../components/schemas/UnauthorizedErrorRep.js";
import type { NotFoundErrorRep } from "../../../../../../../components/schemas/NotFoundErrorRep.js";
import type { RateLimitedErrorRep } from "../../../../../../../components/schemas/RateLimitedErrorRep.js";
import type { patchSegmentExpiringTargetInputRep } from "../../../../../../../components/schemas/patchSegmentExpiringTargetInputRep.js";
import type { ExpiringTargetPatchResponse } from "../../../../../../../components/schemas/ExpiringTargetPatchResponse.js";
import type { InvalidRequestErrorRep } from "../../../../../../../components/schemas/InvalidRequestErrorRep.js";
import type { ForbiddenErrorRep } from "../../../../../../../components/schemas/ForbiddenErrorRep.js";
import type { StatusConflictErrorRep } from "../../../../../../../components/schemas/StatusConflictErrorRep.js";

/**
 * Get a list of a segment's context targets that are scheduled for removal.
 */
export type getExpiringTargetsForSegment = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: getExpiringTargetsForSegment_Path;
    headers: getExpiringTargetsForSegment_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ExpiringTargetGetResponse;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 *
 * Update expiring context targets for a segment. Updating a context target expiration uses the semantic patch format.
 *
 * To make a semantic patch request, you must append `domain-model=launchdarkly.semanticpatch` to your `Content-Type` header. To learn more, read [Updates using semantic patch](/reference#updates-using-semantic-patch).
 *
 * If the request is well-formed but any of its instructions failed to process, this operation returns status code `200`. In this case, the response `errors` array will be non-empty.
 *
 * ### Instructions
 *
 * Semantic patch requests support the following `kind` instructions for updating expiring context targets.
 *
 * <details>
 * <summary>Click to expand instructions for <strong>updating expiring context targets</strong></summary>
 *
 * #### addExpiringTarget
 *
 * Schedules a date and time when LaunchDarkly will remove a context from segment targeting. The segment must already have the context as an individual target.
 *
 * ##### Parameters
 *
 * - `targetType`: The type of individual target for this context. Must be either `included` or `excluded`.
 * - `contextKey`: The context key.
 * - `contextKind`: The kind of context being targeted.
 * - `value`: The date when the context should expire from the segment targeting, in Unix milliseconds.
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "addExpiringTarget",
 *     "targetType": "included",
 *     "contextKey": "user-key-123abc",
 *     "contextKind": "user",
 *     "value": 1754092860000
 *   }]
 * }
 * ```
 *
 * #### updateExpiringTarget
 *
 * Updates the date and time when LaunchDarkly will remove a context from segment targeting.
 *
 * ##### Parameters
 *
 * - `targetType`: The type of individual target for this context. Must be either `included` or `excluded`.
 * - `contextKey`: The context key.
 * - `contextKind`: The kind of context being targeted.
 * - `value`: The new date when the context should expire from the segment targeting, in Unix milliseconds.
 * - `version`: (Optional) The version of the expiring target to update. If included, update will fail if version doesn't match current version of the expiring target.
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "updateExpiringTarget",
 *     "targetType": "included",
 *     "contextKey": "user-key-123abc",
 *     "contextKind": "user",
 *     "value": 1754179260000
 *   }]
 * }
 * ```
 *
 * #### removeExpiringTarget
 *
 * Removes the scheduled expiration for the context in the segment.
 *
 * ##### Parameters
 *
 * - `targetType`: The type of individual target for this context. Must be either `included` or `excluded`.
 * - `contextKey`: The context key.
 * - `contextKind`: The kind of context being targeted.
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "removeExpiringTarget",
 *     "targetType": "included",
 *     "contextKey": "user-key-123abc",
 *     "contextKind": "user",
 *   }]
 * }
 * ```
 *
 * </details>
 *
 */
export type patchExpiringTargetsForSegment = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: patchExpiringTargetsForSegment_Path;
    headers: patchExpiringTargetsForSegment_Headers;
    cookie: never;
    body: patchSegmentExpiringTargetInputRep;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ExpiringTargetPatchResponse;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InvalidRequestErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      409: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: StatusConflictErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type getExpiringTargetsForSegment_Path = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The segment key
   */
  segmentKey: string;
};

export type getExpiringTargetsForSegment_Headers = { Authorization: string };

export type patchExpiringTargetsForSegment_Path = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The segment key
   */
  segmentKey: string;
};

export type patchExpiringTargetsForSegment_Headers = { Authorization: string };
