// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { organization_simple } from "../../../../../../components/schemas/organization-simple.js";

/**
 * Check if an enterprise team is assigned to an organization
 */
export type enterpriseTeamOrganizationsGetAssignment = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: enterpriseTeamOrganizationsGetAssignment_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: organization_simple;
          };
        };
        examples: {
          default: unknown;
        };
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Assign an enterprise team to an organization.
 */
export type enterpriseTeamOrganizationsAdd = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: enterpriseTeamOrganizationsAdd_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: organization_simple;
          };
        };
        examples: {
          default: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Unassign an enterprise team from an organization.
 */
export type enterpriseTeamOrganizationsDelete = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: enterpriseTeamOrganizationsDelete_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type enterpriseTeamOrganizationsGetAssignment_Path = {
  enterprise: string;
  "enterprise-team": string;
  org: string;
};

export type enterpriseTeamOrganizationsAdd_Path = {
  enterprise: string;
  "enterprise-team": string;
  org: string;
};

export type enterpriseTeamOrganizationsDelete_Path = {
  enterprise: string;
  "enterprise-team": string;
  org: string;
};
