// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../../counterfact-types/index.ts";
import type { FlagFollowersGetRep } from "../../../../../../../../../components/schemas/FlagFollowersGetRep.js";
import type { InvalidRequestErrorRep } from "../../../../../../../../../components/schemas/InvalidRequestErrorRep.js";
import type { UnauthorizedErrorRep } from "../../../../../../../../../components/schemas/UnauthorizedErrorRep.js";
import type { ForbiddenErrorRep } from "../../../../../../../../../components/schemas/ForbiddenErrorRep.js";
import type { NotFoundErrorRep } from "../../../../../../../../../components/schemas/NotFoundErrorRep.js";

/**
 * Get a list of members following a flag in a project and environment
 */
export type getFlagFollowers = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: getFlagFollowers_Path;
    headers: getFlagFollowers_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: FlagFollowersGetRep;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InvalidRequestErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type getFlagFollowers_Path = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The feature flag key
   */
  featureFlagKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
};

export type getFlagFollowers_Headers = { Authorization: string };
