// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { actions_cache_list } from "../../../../../components/schemas/actions-cache-list.js";

/**
 * Lists the GitHub Actions caches for a repository.
 *
 * OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
 */
export type actionsGetActionsCacheList = (
  $: OmitValueWhenNever<{
    query: actionsGetActionsCacheList_Query;
    querystring: never;
    path: actionsGetActionsCacheList_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: actions_cache_list;
          };
        };
        examples: {
          default: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Deletes one or more GitHub Actions caches for a repository, using a complete cache key. By default, all caches that match the provided key are deleted, but you can optionally provide a Git ref to restrict deletions to caches that match both the provided key and the Git ref.
 *
 * OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
 */
export type actionsDeleteActionsCacheByKey = (
  $: OmitValueWhenNever<{
    query: actionsDeleteActionsCacheByKey_Query;
    querystring: never;
    path: actionsDeleteActionsCacheByKey_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: actions_cache_list;
          };
        };
        examples: {
          default: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type actionsGetActionsCacheList_Query = {
  per_page?: number;
  page?: number;
  ref?: string;
  key?: string;
  sort?: "created_at" | "last_accessed_at" | "size_in_bytes";
  direction?: "asc" | "desc";
};

export type actionsGetActionsCacheList_Path = { owner: string; repo: string };

export type actionsDeleteActionsCacheByKey_Query = {
  key: string;
  ref?: string;
};

export type actionsDeleteActionsCacheByKey_Path = {
  owner: string;
  repo: string;
};
