// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { copilot_space } from "../../../../components/schemas/copilot-space.js";
import type { forbidden } from "../../../../#/components/responses/forbidden.js";
import type { not_found } from "../../../../#/components/responses/not_found.js";
import type { validation_failed } from "../../../../#/components/responses/validation_failed.js";

/**
 * Gets details about a specific Copilot Space owned by a user. The authenticated user must have read access to the Space.
 *
 * Private user spaces require the authenticated user to be the owner of the space.
 * Public user spaces are accessible to any authenticated user.
 *
 * OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
 */
export type copilotSpacesGetForUser = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: copilotSpacesGetForUser_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: copilot_space;
          };
        };
        examples: {
          default: unknown;
        };
      };
      403: forbidden;
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Updates a Copilot Space owned by a user. Only the authenticated user can update spaces for their own account.
 *
 * Users can update their personal Copilot Spaces.
 *
 * OAuth app tokens and personal access tokens (classic) need the `read:user` scope to use this endpoint.
 */
export type copilotSpacesUpdateForUser = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: copilotSpacesUpdateForUser_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * The name of the Copilot Space.
       * @example "Updated Development Space"
       */
      name?: string;
      /**
       * A description of the Copilot Space.
       * @example "Updated personal space for development assistance"
       */
      description?: string;
      /**
       * General instructions for the Copilot Space.
       * @example "Updated instructions to help me with React development patterns and best practices"
       */
      general_instructions?: string;
      /**
       * The base role that determines default permissions for the space. Changing this field requires admin permissions.
       * - `no_access`: No default access (default)
       * - `reader`: Makes the space publicly readable
       * Note: User spaces do not support writer or admin base roles.
       */
      base_role?: "reader" | "no_access";
      /**
       * Resources to attach to the space.
       */
      resources_attributes?: Array<{
        /**
         * The type of resource.
         */
        resource_type?:
          | "repository"
          | "github_file"
          | "free_text"
          | "github_issue"
          | "github_pull_request"
          | "media_content"
          | "uploaded_text_file";
        /**
         * Metadata specific to the resource type.
         */
        metadata?: {
          /**
           * Repository ID for repository or file resources.
           */
          repository_id?: number;
          /**
           * File path for file resources.
           */
          file_path?: string;
          /**
           * Text content for free text resources.
           */
          text?: string;
          /**
           * Name for the resource.
           */
          name?: string;
          /**
           * Issue or PR number.
           */
          number?: number;
        };
      }>;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: copilot_space;
          };
        };
        examples: {
          default: unknown;
        };
      };
      403: forbidden;
      404: not_found;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Deletes a Copilot Space owned by a user. The authenticated user must be the owner of the space.
 *
 * **Warning:** This action is permanent and cannot be undone. Deleting a space will remove all associated resources and configurations.
 *
 * OAuth app tokens and personal access tokens (classic) need the `user` scope to use this endpoint.
 */
export type copilotSpacesDeleteForUser = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: copilotSpacesDeleteForUser_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      404: not_found;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type copilotSpacesGetForUser_Path = {
  username: string;
  /**
   * The unique identifier of the Copilot Space.
   */
  space_number: number;
};

export type copilotSpacesUpdateForUser_Path = {
  username: string;
  /**
   * The unique identifier of the Copilot Space.
   */
  space_number: number;
};

export type copilotSpacesDeleteForUser_Path = {
  username: string;
  /**
   * The unique identifier of the Copilot Space.
   */
  space_number: number;
};
