// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { porter_author } from "../../../../../../components/schemas/porter-author.js";
import type { not_found } from "../../../../../../#/components/responses/not_found.js";
import type { validation_failed } from "../../../../../../#/components/responses/validation_failed.js";
import type { porter_maintenance } from "../../../../../../#/components/responses/porter_maintenance.js";

/**
 * Update an author's identity for the import. Your application can continue updating authors any time before you push
 * new commits to the repository.
 *
 * > [!WARNING]
 * > **Endpoint closing down notice:** Due to very low levels of usage and available alternatives, this endpoint is closing down and will no longer be available from 00:00 UTC on April 12, 2024. For more details and alternatives, see the [changelog](https://gh.io/source-imports-api-deprecation).
 * @deprecated
 */
export type migrationsMapCommitAuthor = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: migrationsMapCommitAuthor_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * The new Git author email.
       */
      email?: string;
      /**
       * The new Git author name.
       */
      name?: string;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: porter_author;
          };
        };
        examples: {
          default: unknown;
        };
      };
      404: not_found;
      422: validation_failed;
      503: porter_maintenance;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type migrationsMapCommitAuthor_Path = {
  owner: string;
  repo: string;
  author_id: number;
};
