// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { api_insights_route_stats } from "../../../../../../../components/schemas/api-insights-route-stats.js";

/**
 * Get API request count statistics for an actor broken down by route within a specified time frame.
 */
export type apiInsightsGetRouteStatsByActor = (
  $: OmitValueWhenNever<{
    query: apiInsightsGetRouteStatsByActor_Query;
    querystring: never;
    path: apiInsightsGetRouteStatsByActor_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: api_insights_route_stats;
          };
        };
        examples: {
          default: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type apiInsightsGetRouteStatsByActor_Query = {
  min_timestamp: string;
  max_timestamp?: string;
  page?: number;
  per_page?: number;
  direction?: "asc" | "desc";
  sort?: Array<
    | "last_rate_limited_timestamp"
    | "last_request_timestamp"
    | "rate_limited_request_count"
    | "http_method"
    | "api_route"
    | "total_request_count"
  >;
  api_route_substring?: string;
};

export type apiInsightsGetRouteStatsByActor_Path = {
  org: string;
  actor_type:
    | "installation"
    | "classic_pat"
    | "fine_grained_pat"
    | "oauth_app"
    | "github_app_user_to_server";
  actor_id: number;
};
