// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { repository_advisory } from "../../../../../components/schemas/repository-advisory.js";
import type { forbidden } from "../../../../../#/components/responses/forbidden.js";
import type { not_found } from "../../../../../#/components/responses/not_found.js";
import type { repository_advisory_update } from "../../../../../components/schemas/repository-advisory-update.js";
import type { validation_error } from "../../../../../components/schemas/validation-error.js";

/**
 * Get a repository security advisory using its GitHub Security Advisory (GHSA) identifier.
 *
 * Anyone can access any published security advisory on a public repository.
 *
 * The authenticated user can access an unpublished security advisory from a repository if they are a security manager or administrator of that repository, or if they are a
 * collaborator on the security advisory.
 *
 * OAuth app tokens and personal access tokens (classic) need the `repo` or `repository_advisories:read` scope to to get a published security advisory in a private repository, or any unpublished security advisory that the authenticated user has access to.
 */
export type securityAdvisoriesGetRepositoryAdvisory = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: securityAdvisoriesGetRepositoryAdvisory_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: repository_advisory;
          };
        };
        examples: {
          default: unknown;
        };
      };
      403: forbidden;
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Update a repository security advisory using its GitHub Security Advisory (GHSA) identifier.
 *
 * In order to update any security advisory, the authenticated user must be a security manager or administrator of that repository,
 * or a collaborator on the repository security advisory.
 *
 * OAuth app tokens and personal access tokens (classic) need the `repo` or `repository_advisories:write` scope to use this endpoint.
 */
export type securityAdvisoriesUpdateRepositoryAdvisory = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: securityAdvisoriesUpdateRepositoryAdvisory_Path;
    headers: never;
    cookie: never;
    body: repository_advisory_update;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: repository_advisory;
          };
        };
        examples: {
          default: unknown;
          add_credit: unknown;
        };
      };
      403: forbidden;
      404: not_found;
      422: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: validation_error;
          };
        };
        examples: {
          invalid_state_transition: unknown;
          update_severity_with_cvss_set: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type securityAdvisoriesGetRepositoryAdvisory_Path = {
  owner: string;
  repo: string;
  ghsa_id: string;
};

export type securityAdvisoriesUpdateRepositoryAdvisory_Path = {
  owner: string;
  repo: string;
  ghsa_id: string;
};
