// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { reaction } from "../../../../../../components/schemas/reaction.js";
import type { not_found } from "../../../../../../#/components/responses/not_found.js";
import type { validation_failed } from "../../../../../../#/components/responses/validation_failed.js";

/**
 * List the reactions to a [release](https://docs.github.com/rest/releases/releases#get-a-release).
 */
export type reactionsListForRelease = (
  $: OmitValueWhenNever<{
    query: reactionsListForRelease_Query;
    querystring: never;
    path: reactionsListForRelease_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<reaction>;
          };
        };
        examples: {
          default: unknown;
        };
      };
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Create a reaction to a [release](https://docs.github.com/rest/releases/releases#get-a-release). A response with a `Status: 200 OK` means that you already added the reaction type to this release.
 */
export type reactionsCreateForRelease = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: reactionsCreateForRelease_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * The [reaction type](https://docs.github.com/rest/reactions/reactions#about-reactions) to add to the release.
       */
      content: "+1" | "laugh" | "heart" | "hooray" | "rocket" | "eyes";
    };
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: reaction;
          };
        };
        examples: {
          default: unknown;
        };
      };
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: reaction;
          };
        };
        examples: {
          default: unknown;
        };
      };
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type reactionsListForRelease_Query = {
  /**
   * Returns a single [reaction type](https://docs.github.com/rest/reactions/reactions#about-reactions). Omit this parameter to list all reactions to a release.
   */
  content?: "+1" | "laugh" | "heart" | "hooray" | "rocket" | "eyes";
  per_page?: number;
  page?: number;
};

export type reactionsListForRelease_Path = {
  owner: string;
  repo: string;
  release_id: number;
};

export type reactionsCreateForRelease_Path = {
  owner: string;
  repo: string;
  release_id: number;
};
