// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { codespaces_org_secret } from "../../../../../components/schemas/codespaces-org-secret.js";
import type { empty_object } from "../../../../../components/schemas/empty-object.js";
import type { not_found } from "../../../../../#/components/responses/not_found.js";
import type { validation_failed } from "../../../../../#/components/responses/validation_failed.js";

/**
 * Gets an organization development environment secret without revealing its encrypted value.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint.
 */
export type codespacesGetOrgSecret = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: codespacesGetOrgSecret_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: codespaces_org_secret;
          };
        };
        examples: {
          default: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Creates or updates an organization development environment secret with an encrypted value. Encrypt your secret using
 * [LibSodium](https://libsodium.gitbook.io/doc/bindings_for_other_languages). For more information, see "[Encrypting secrets for the REST API](https://docs.github.com/rest/guides/encrypting-secrets-for-the-rest-api)."
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint.
 */
export type codespacesCreateOrUpdateOrgSecret = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: codespacesCreateOrUpdateOrgSecret_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * The value for your secret, encrypted with [LibSodium](https://libsodium.gitbook.io/doc/bindings_for_other_languages) using the public key retrieved from the [Get an organization public key](https://docs.github.com/rest/codespaces/organization-secrets#get-an-organization-public-key) endpoint.
       */
      encrypted_value?: string;
      /**
       * The ID of the key you used to encrypt the secret.
       */
      key_id?: string;
      /**
       * Which type of organization repositories have access to the organization secret. `selected` means only the repositories specified by `selected_repository_ids` can access the secret.
       */
      visibility: "all" | "private" | "selected";
      /**
       * An array of repository IDs that can access the organization secret. You can only provide a list of repository IDs when the `visibility` is set to `selected`. You can manage the list of selected repositories using the [List selected repositories for an organization secret](https://docs.github.com/rest/codespaces/organization-secrets#list-selected-repositories-for-an-organization-secret), [Set selected repositories for an organization secret](https://docs.github.com/rest/codespaces/organization-secrets#set-selected-repositories-for-an-organization-secret), and [Remove selected repository from an organization secret](https://docs.github.com/rest/codespaces/organization-secrets#remove-selected-repository-from-an-organization-secret) endpoints.
       */
      selected_repository_ids?: Array<number>;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: empty_object;
          };
        };
        examples: {
          default: unknown;
        };
      };
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      404: not_found;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Deletes an organization development environment secret using the secret name.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint.
 */
export type codespacesDeleteOrgSecret = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: codespacesDeleteOrgSecret_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type codespacesGetOrgSecret_Path = { org: string; secret_name: string };

export type codespacesCreateOrUpdateOrgSecret_Path = {
  org: string;
  secret_name: string;
};

export type codespacesDeleteOrgSecret_Path = {
  org: string;
  secret_name: string;
};
