// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../counterfact-types/index.ts";
import type { Context } from "../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../counterfact-types/index.ts";
import type { classroom_accepted_assignment } from "../../../components/schemas/classroom-accepted-assignment.js";

/**
 * Lists any assignment repositories that have been created by students accepting a GitHub Classroom assignment. Accepted assignments will only be returned if the current user is an administrator of the GitHub Classroom for the assignment.
 */
export type classroomListAcceptedAssignmentsForAnAssignment = (
  $: OmitValueWhenNever<{
    query: classroomListAcceptedAssignmentsForAnAssignment_Query;
    querystring: never;
    path: classroomListAcceptedAssignmentsForAnAssignment_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<classroom_accepted_assignment>;
          };
        };
        examples: {
          default: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type classroomListAcceptedAssignmentsForAnAssignment_Query = {
  page?: number;
  per_page?: number;
};

export type classroomListAcceptedAssignmentsForAnAssignment_Path = {
  assignment_id: number;
};
