// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { dependabot_alert_with_repository } from "../../../../components/schemas/dependabot-alert-with-repository.js";
import type { not_modified } from "../../../../#/components/responses/not_modified.js";
import type { bad_request } from "../../../../#/components/responses/bad_request.js";
import type { forbidden } from "../../../../#/components/responses/forbidden.js";
import type { not_found } from "../../../../#/components/responses/not_found.js";
import type { validation_failed_simple } from "../../../../#/components/responses/validation_failed_simple.js";

/**
 * Lists Dependabot alerts for an organization.
 *
 * The authenticated user must be an owner or security manager for the organization to use this endpoint.
 *
 * OAuth app tokens and personal access tokens (classic) need the `security_events` scope to use this endpoint. If this endpoint is only used with public repositories, the token can use the `public_repo` scope instead.
 */
export type dependabotListAlertsForOrg = (
  $: OmitValueWhenNever<{
    query: dependabotListAlertsForOrg_Query;
    querystring: never;
    path: dependabotListAlertsForOrg_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<dependabot_alert_with_repository>;
          };
        };
        examples: {
          default: unknown;
        };
      };
      304: not_modified;
      400: bad_request;
      403: forbidden;
      404: not_found;
      422: validation_failed_simple;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type dependabotListAlertsForOrg_Query = {
  classification?: string;
  state?: string;
  severity?: string;
  ecosystem?: string;
  package?: string;
  epss_percentage?: string;
  artifact_registry_url?: string;
  artifact_registry?: string;
  has?: string | Array<"patch" | "deployment">;
  assignee?: string;
  runtime_risk?: string;
  scope?: "development" | "runtime";
  sort?: "created" | "updated" | "epss_percentage";
  direction?: "asc" | "desc";
  before?: string;
  after?: string;
  per_page?: number;
};

export type dependabotListAlertsForOrg_Path = { org: string };
