// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { pull_request_merge_result } from "../../../../../../components/schemas/pull-request-merge-result.js";
import type { forbidden } from "../../../../../../#/components/responses/forbidden.js";
import type { not_found } from "../../../../../../#/components/responses/not_found.js";
import type { validation_failed } from "../../../../../../#/components/responses/validation_failed.js";

/**
 * Checks if a pull request has been merged into the base branch. The HTTP status of the response indicates whether or not the pull request has been merged; the response body is empty.
 */
export type pullsCheckIfMerged = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: pullsCheckIfMerged_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Merges a pull request into the base branch.
 * This endpoint triggers [notifications](https://docs.github.com/github/managing-subscriptions-and-notifications-on-github/about-notifications). Creating content too quickly using this endpoint may result in secondary rate limiting. For more information, see "[Rate limits for the API](https://docs.github.com/rest/using-the-rest-api/rate-limits-for-the-rest-api#about-secondary-rate-limits)" and "[Best practices for using the REST API](https://docs.github.com/rest/guides/best-practices-for-using-the-rest-api)."
 */
export type pullsMerge = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: pullsMerge_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * Title for the automatic commit message.
       */
      commit_title?: string;
      /**
       * Extra detail to append to automatic commit message.
       */
      commit_message?: string;
      /**
       * SHA that pull request head must match to allow merge.
       */
      sha?: string;
      /**
       * The merge method to use.
       */
      merge_method?: "merge" | "squash" | "rebase";
    };
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: pull_request_merge_result;
          };
        };
        examples: {
          "response-if-merge-was-successful": unknown;
        };
      };
      403: forbidden;
      404: not_found;
      405: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: { message?: string; documentation_url?: string };
          };
        };
        examples: {
          "response-if-merge-cannot-be-performed": unknown;
        };
      };
      409: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: { message?: string; documentation_url?: string };
          };
        };
        examples: {
          "response-if-sha-was-provided-and-pull-request-head-did-not-match": unknown;
        };
      };
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type pullsCheckIfMerged_Path = {
  owner: string;
  repo: string;
  pull_number: number;
};

export type pullsMerge_Path = {
  owner: string;
  repo: string;
  pull_number: number;
};
