// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { forbidden } from "../../../../../../#/components/responses/forbidden.js";
import type { validation_failed } from "../../../../../../#/components/responses/validation_failed.js";

/**
 * Updates the pull request branch with the latest upstream changes by merging HEAD from the base branch into the pull request branch.
 * Note: If making a request on behalf of a GitHub App you must also have permissions to write the contents of the head repository.
 */
export type pullsUpdateBranch = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: pullsUpdateBranch_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * The expected SHA of the pull request's HEAD ref. This is the most recent commit on the pull request's branch. If the expected SHA does not match the pull request's HEAD, you will receive a `422 Unprocessable Entity` status. You can use the "[List commits](https://docs.github.com/rest/commits/commits#list-commits)" endpoint to find the most recent commit SHA. Default: SHA of the pull request's current HEAD ref.
       */
      expected_head_sha?: string;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      202: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: { message?: string; url?: string };
          };
        };
        examples: {
          default: unknown;
        };
      };
      403: forbidden;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type pullsUpdateBranch_Path = {
  owner: string;
  repo: string;
  pull_number: number;
};
