// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../counterfact-types/index.ts";
import type { Context } from "../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../counterfact-types/index.ts";
import type { Address } from "../../components/schemas/Address.js";
import type { AuthenticationFailed } from "../../#/components/responses/AuthenticationFailed.js";
import type { NotFound } from "../../#/components/responses/NotFound.js";

/**
 * Retrieves an address for an individual customer. Source reviewed 2026-08-02:
 * https://developer.ordergroove.com/reference/addresses-retrieve
 *
 */
export type addressesRetrieve = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: addressesRetrieve_Path;
    headers: addressesRetrieve_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Address;
          };
        };
        examples: {};
      };
      403: AuthenticationFailed;
      404: NotFound;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type addressesRetrieve_Path = { address_id: string };

export type addressesRetrieve_Headers = {
  "x-api-key": string;
  Authorization: string;
};
