// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";

/**
 * > [!NOTE]
 * > This endpoint is in public preview and is subject to change.
 *
 * Returns a list of tasks for a specific repository
 *
 * **Fine-grained access tokens for "List tasks for repository"**
 *
 * This endpoint works with the following fine-grained token types:
 *
 * * [GitHub App user access tokens](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-user-access-token-for-a-github-app)
 * * [Fine-grained personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token)
 *
 * The fine-grained token must have the following permission set:
 *
 * * "Agent tasks" repository permissions (read)
 *
 * GitHub App installation access tokens are not supported for this endpoint.
 *
 */
export type agentTasksListTasksForRepo = (
  $: OmitValueWhenNever<{
    query: agentTasksListTasksForRepo_Query;
    querystring: never;
    path: agentTasksListTasksForRepo_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              /**
               * List of tasks
               */
              tasks: Array<{
                /**
                 * Unique task identifier
                 */
                id: string;
                /**
                 * API URL for this task
                 */
                url?: string;
                /**
                 * Web URL for this task
                 */
                html_url?: string;
                /**
                 * Human-readable name derived from the task prompt
                 */
                name?: string;
                /**
                 * The entity who created this task
                 */
                creator?: {
                  /**
                   * The unique identifier of the user
                   * @format int64
                   */
                  id?: number;
                };
                /**
                 * Type of the task creator
                 */
                creator_type?: "user" | "organization";
                /**
                 * User objects of collaborators on this task
                 * @deprecated
                 */
                user_collaborators?: Array<{
                  /**
                   * The unique identifier of the user
                   * @format int64
                   */
                  id?: number;
                }>;
                /**
                 * The owner of the repository
                 */
                owner?: {
                  /**
                   * The unique identifier of the user
                   * @format int64
                   */
                  id?: number;
                };
                /**
                 * The repository this task belongs to
                 */
                repository?: {
                  /**
                   * The unique identifier of the repository
                   * @format int64
                   */
                  id?: number;
                };
                /**
                 * Current state of the task, derived from its most recent session
                 */
                state:
                  | "queued"
                  | "in_progress"
                  | "completed"
                  | "failed"
                  | "idle"
                  | "waiting_for_user"
                  | "timed_out"
                  | "cancelled";
                /**
                 * Number of sessions in this task
                 * @format int32
                 */
                session_count?: number;
                /**
                 * Resources created by this task (PRs, branches, etc.)
                 */
                artifacts?: Array<{
                  /**
                   * Provider namespace
                   */
                  provider: "github";
                  /**
                   * Type of artifact. Available Values: `pull`, `branch`.
                   *
                   */
                  type: "pull" | "branch";
                  /**
                   * Resource data (shape depends on type)
                   */
                  data:
                    | {
                        /**
                         * GitHub resource ID
                         * @format int64
                         */
                        id: number;
                        /**
                         * GraphQL global ID
                         */
                        global_id?: string;
                      }
                    | {
                        /**
                         * Head branch name
                         */
                        head_ref: string;
                        /**
                         * Base branch name
                         */
                        base_ref: string;
                      };
                }>;
                /**
                 * Timestamp when the task was archived, null if not archived
                 * @format date-time
                 */
                archived_at?: string;
                /**
                 * Timestamp of the most recent update
                 * @format date-time
                 */
                updated_at?: string;
                /**
                 * Timestamp when the task was created
                 * @format date-time
                 */
                created_at: string;
              }>;
              /**
               * Total count of active (non-archived) tasks
               * @format int32
               */
              total_active_count?: number;
              /**
               * Total count of archived tasks
               * @format int32
               */
              total_archived_count?: number;
            };
          };
        };
        examples: {
          default: unknown;
        };
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              /**
               * Summary message (e.g. "Validation Failed", "Not Found")
               */
              message: string;
              /**
               * List of validation errors (present only for 422 responses)
               */
              errors?: Array<{
                /**
                 * Machine-readable error code
                 */
                code:
                  | "missing"
                  | "missing_field"
                  | "invalid"
                  | "already_exists"
                  | "unprocessable"
                  | "custom";
                /**
                 * Human-readable message (populated when code is "custom")
                 */
                message?: string;
              }>;
              /**
               * URL to relevant API documentation
               */
              documentation_url: string;
            };
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              /**
               * Summary message (e.g. "Validation Failed", "Not Found")
               */
              message: string;
              /**
               * List of validation errors (present only for 422 responses)
               */
              errors?: Array<{
                /**
                 * Machine-readable error code
                 */
                code:
                  | "missing"
                  | "missing_field"
                  | "invalid"
                  | "already_exists"
                  | "unprocessable"
                  | "custom";
                /**
                 * Human-readable message (populated when code is "custom")
                 */
                message?: string;
              }>;
              /**
               * URL to relevant API documentation
               */
              documentation_url: string;
            };
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              /**
               * Summary message (e.g. "Validation Failed", "Not Found")
               */
              message: string;
              /**
               * List of validation errors (present only for 422 responses)
               */
              errors?: Array<{
                /**
                 * Machine-readable error code
                 */
                code:
                  | "missing"
                  | "missing_field"
                  | "invalid"
                  | "already_exists"
                  | "unprocessable"
                  | "custom";
                /**
                 * Human-readable message (populated when code is "custom")
                 */
                message?: string;
              }>;
              /**
               * URL to relevant API documentation
               */
              documentation_url: string;
            };
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              /**
               * Summary message (e.g. "Validation Failed", "Not Found")
               */
              message: string;
              /**
               * List of validation errors (present only for 422 responses)
               */
              errors?: Array<{
                /**
                 * Machine-readable error code
                 */
                code:
                  | "missing"
                  | "missing_field"
                  | "invalid"
                  | "already_exists"
                  | "unprocessable"
                  | "custom";
                /**
                 * Human-readable message (populated when code is "custom")
                 */
                message?: string;
              }>;
              /**
               * URL to relevant API documentation
               */
              documentation_url: string;
            };
          };
        };
        examples: {};
      };
      422: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              /**
               * Summary message (e.g. "Validation Failed", "Not Found")
               */
              message: string;
              /**
               * List of validation errors (present only for 422 responses)
               */
              errors?: Array<{
                /**
                 * Machine-readable error code
                 */
                code:
                  | "missing"
                  | "missing_field"
                  | "invalid"
                  | "already_exists"
                  | "unprocessable"
                  | "custom";
                /**
                 * Human-readable message (populated when code is "custom")
                 */
                message?: string;
              }>;
              /**
               * URL to relevant API documentation
               */
              documentation_url: string;
            };
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * > [!NOTE]
 * > This endpoint is in public preview and is subject to change.
 *
 * Starts a new Copilot cloud agent task for a repository.
 *
 * This endpoint is only available to users with a Copilot Business or Copilot Enterprise subscription.
 *
 * **Fine-grained access tokens for "Start a task"**
 *
 * This endpoint works with the following fine-grained token types:
 *
 * * [GitHub App user access tokens](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-user-access-token-for-a-github-app)
 * * [Fine-grained personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token)
 *
 * The fine-grained token must have the following permission set:
 *
 * * "Agent tasks" repository permissions (read and write)
 *
 * GitHub App installation access tokens are not supported for this endpoint.
 *
 */
export type agentTasksCreateTaskInRepo = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: agentTasksCreateTaskInRepo_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * The user's prompt for the agent
       */
      prompt: string;
      /**
       * The model to use for this task. The allowed models may change over time and depend on the user's GitHub Copilot plan and organization policies. Currently supported values: `claude-sonnet-4.6`, `claude-opus-4.6`, `gpt-5.2-codex`, `gpt-5.3-codex`, `gpt-5.4`, `claude-sonnet-4.5`, `claude-opus-4.5`
       */
      model?: string;
      /**
       * Whether to create a PR.
       * @default false
       */
      create_pull_request?: boolean;
      /**
       * Base ref for new branch/PR
       */
      base_ref?: string;
      /**
       * Head ref for existing branch/PR. If provided with `base_ref`, the agent looks up open PR context for `head_ref` targeting `base_ref` and commits to `head_ref` instead of creating a new branch.
       */
      head_ref?: string;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              /**
               * Unique task identifier
               */
              id: string;
              /**
               * API URL for this task
               */
              url?: string;
              /**
               * Web URL for this task
               */
              html_url?: string;
              /**
               * Human-readable name derived from the task prompt
               */
              name?: string;
              /**
               * The entity who created this task
               */
              creator?: {
                /**
                 * The unique identifier of the user
                 * @format int64
                 */
                id?: number;
              };
              /**
               * Type of the task creator
               */
              creator_type?: "user" | "organization";
              /**
               * User objects of collaborators on this task
               * @deprecated
               */
              user_collaborators?: Array<{
                /**
                 * The unique identifier of the user
                 * @format int64
                 */
                id?: number;
              }>;
              /**
               * The owner of the repository
               */
              owner?: {
                /**
                 * The unique identifier of the user
                 * @format int64
                 */
                id?: number;
              };
              /**
               * The repository this task belongs to
               */
              repository?: {
                /**
                 * The unique identifier of the repository
                 * @format int64
                 */
                id?: number;
              };
              /**
               * Current state of the task, derived from its most recent session
               */
              state:
                | "queued"
                | "in_progress"
                | "completed"
                | "failed"
                | "idle"
                | "waiting_for_user"
                | "timed_out"
                | "cancelled";
              /**
               * Number of sessions in this task
               * @format int32
               */
              session_count?: number;
              /**
               * Resources created by this task (PRs, branches, etc.)
               */
              artifacts?: Array<{
                /**
                 * Provider namespace
                 */
                provider: "github";
                /**
                 * Type of artifact. Available Values: `pull`, `branch`.
                 *
                 */
                type: "pull" | "branch";
                /**
                 * Resource data (shape depends on type)
                 */
                data:
                  | {
                      /**
                       * GitHub resource ID
                       * @format int64
                       */
                      id: number;
                      /**
                       * GraphQL global ID
                       */
                      global_id?: string;
                    }
                  | {
                      /**
                       * Head branch name
                       */
                      head_ref: string;
                      /**
                       * Base branch name
                       */
                      base_ref: string;
                    };
              }>;
              /**
               * Timestamp when the task was archived, null if not archived
               * @format date-time
               */
              archived_at?: string;
              /**
               * Timestamp of the most recent update
               * @format date-time
               */
              updated_at?: string;
              /**
               * Timestamp when the task was created
               * @format date-time
               */
              created_at: string;
            };
          };
        };
        examples: {
          default: unknown;
        };
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              /**
               * Summary message (e.g. "Validation Failed", "Not Found")
               */
              message: string;
              /**
               * List of validation errors (present only for 422 responses)
               */
              errors?: Array<{
                /**
                 * Machine-readable error code
                 */
                code:
                  | "missing"
                  | "missing_field"
                  | "invalid"
                  | "already_exists"
                  | "unprocessable"
                  | "custom";
                /**
                 * Human-readable message (populated when code is "custom")
                 */
                message?: string;
              }>;
              /**
               * URL to relevant API documentation
               */
              documentation_url: string;
            };
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              /**
               * Summary message (e.g. "Validation Failed", "Not Found")
               */
              message: string;
              /**
               * List of validation errors (present only for 422 responses)
               */
              errors?: Array<{
                /**
                 * Machine-readable error code
                 */
                code:
                  | "missing"
                  | "missing_field"
                  | "invalid"
                  | "already_exists"
                  | "unprocessable"
                  | "custom";
                /**
                 * Human-readable message (populated when code is "custom")
                 */
                message?: string;
              }>;
              /**
               * URL to relevant API documentation
               */
              documentation_url: string;
            };
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              /**
               * Summary message (e.g. "Validation Failed", "Not Found")
               */
              message: string;
              /**
               * List of validation errors (present only for 422 responses)
               */
              errors?: Array<{
                /**
                 * Machine-readable error code
                 */
                code:
                  | "missing"
                  | "missing_field"
                  | "invalid"
                  | "already_exists"
                  | "unprocessable"
                  | "custom";
                /**
                 * Human-readable message (populated when code is "custom")
                 */
                message?: string;
              }>;
              /**
               * URL to relevant API documentation
               */
              documentation_url: string;
            };
          };
        };
        examples: {};
      };
      422: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              /**
               * Summary message (e.g. "Validation Failed", "Not Found")
               */
              message: string;
              /**
               * List of validation errors (present only for 422 responses)
               */
              errors?: Array<{
                /**
                 * Machine-readable error code
                 */
                code:
                  | "missing"
                  | "missing_field"
                  | "invalid"
                  | "already_exists"
                  | "unprocessable"
                  | "custom";
                /**
                 * Human-readable message (populated when code is "custom")
                 */
                message?: string;
              }>;
              /**
               * URL to relevant API documentation
               */
              documentation_url: string;
            };
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type agentTasksListTasksForRepo_Query = {
  /**
   * The number of results per page (max 100).
   */
  per_page?: number;
  /**
   * The page number of the results to fetch.
   */
  page?: number;
  /**
   * The field to sort results by. Can be `updated_at` or `created_at`.
   */
  sort?: "updated_at" | "created_at";
  /**
   * The direction to sort results. Can be `asc` or `desc`.
   */
  direction?: "asc" | "desc";
  /**
   * Comma-separated list of task states to filter by. Can be any combination of: `queued`, `in_progress`, `completed`, `failed`, `idle`, `waiting_for_user`, `timed_out`, `cancelled`.
   */
  state?: string;
  /**
   * Filter by archived status. When `true`, returns only archived tasks. When `false` or omitted, returns only non-archived tasks. Defaults to `false`.
   */
  is_archived?: boolean;
  /**
   * Only show tasks updated at or after this time (ISO 8601 timestamp)
   */
  since?: string;
  /**
   * Filter tasks by creator user ID. Accepts one or more user IDs.
   */
  creator_id?: Array<number>;
};

export type agentTasksListTasksForRepo_Path = {
  /**
   * The account owner of the repository. The name is not case sensitive.
   */
  owner: string;
  /**
   * The name of the repository. The name is not case sensitive.
   */
  repo: string;
};

export type agentTasksCreateTaskInRepo_Path = {
  /**
   * The account owner of the repository. The name is not case sensitive.
   */
  owner: string;
  /**
   * The name of the repository. The name is not case sensitive.
   */
  repo: string;
};
