// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { Project } from "../../../../components/schemas/Project.js";
import type { InvalidRequestErrorRep } from "../../../../components/schemas/InvalidRequestErrorRep.js";
import type { UnauthorizedErrorRep } from "../../../../components/schemas/UnauthorizedErrorRep.js";
import type { ForbiddenErrorRep } from "../../../../components/schemas/ForbiddenErrorRep.js";
import type { NotFoundErrorRep } from "../../../../components/schemas/NotFoundErrorRep.js";
import type { RateLimitedErrorRep } from "../../../../components/schemas/RateLimitedErrorRep.js";
import type { JSONPatch } from "../../../../components/schemas/JSONPatch.js";
import type { ProjectRep } from "../../../../components/schemas/ProjectRep.js";
import type { StatusConflictErrorRep } from "../../../../components/schemas/StatusConflictErrorRep.js";

/**
 * Get a single project by key.
 *
 * ### Expanding the project response
 *
 * LaunchDarkly supports one field for expanding the "Get project" response. By default, these fields are **not** included in the response.
 *
 * To expand the response, append the `expand` query parameter and add a comma-separated list with any of the following fields:
 * * `environments` includes a paginated list of the project environments.
 *
 * For example, `expand=environments` includes the `environments` field for the project in the response.
 *
 */
export type getProject = (
  $: OmitValueWhenNever<{
    query: getProject_Query;
    querystring: never;
    path: getProject_Path;
    headers: getProject_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Project;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InvalidRequestErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Update a project. Updating a project uses a [JSON patch](https://datatracker.ietf.org/doc/html/rfc6902) representation of the desired changes. To learn more, read [Updates](/#section/Overview/Updates).<br/><br/>To add an element to the project fields that are arrays, set the `path` to the name of the field and then append `/<array index>`. Use `/0` to add to the beginning of the array. Use `/-` to add to the end of the array.
 */
export type patchProject = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: patchProject_Path;
    headers: patchProject_Headers;
    cookie: never;
    body: JSONPatch;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ProjectRep;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InvalidRequestErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      409: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: StatusConflictErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Delete a project by key. Use this endpoint with caution. Deleting a project will delete all associated environments and feature flags. You cannot delete the last project in an account.
 */
export type deleteProject = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: deleteProject_Path;
    headers: deleteProject_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InvalidRequestErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type getProject_Query = {
  /**
   * A comma-separated list of properties that can reveal additional information in the response.
   */
  expand?: string;
};

export type getProject_Path = {
  /**
   * The project key.
   */
  projectKey: string;
};

export type getProject_Headers = { Authorization: string };

export type patchProject_Path = {
  /**
   * The project key
   */
  projectKey: string;
};

export type patchProject_Headers = { Authorization: string };

export type deleteProject_Path = {
  /**
   * The project key
   */
  projectKey: string;
};

export type deleteProject_Headers = { Authorization: string };
