// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { UserSegment } from "../../../../../../components/schemas/UserSegment.js";
import type { UnauthorizedErrorRep } from "../../../../../../components/schemas/UnauthorizedErrorRep.js";
import type { NotFoundErrorRep } from "../../../../../../components/schemas/NotFoundErrorRep.js";
import type { RateLimitedErrorRep } from "../../../../../../components/schemas/RateLimitedErrorRep.js";
import type { PatchWithComment } from "../../../../../../components/schemas/PatchWithComment.js";
import type { InvalidRequestErrorRep } from "../../../../../../components/schemas/InvalidRequestErrorRep.js";
import type { ForbiddenErrorRep } from "../../../../../../components/schemas/ForbiddenErrorRep.js";
import type { StatusConflictErrorRep } from "../../../../../../components/schemas/StatusConflictErrorRep.js";

/**
 * Get a single segment by key.<br/><br/>Segments can be rule-based, list-based, or synced. Big segments include larger list-based segments and synced segments. Some fields in the response only apply to big segments.
 */
export type getSegment = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: getSegment_Path;
    headers: getSegment_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UserSegment;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Update a segment. The request body must be a valid semantic patch, JSON patch, or JSON merge patch. To learn more the different formats, read [Updates](/#section/Overview/Updates).
 *
 * ### Using semantic patches on a segment
 *
 * To make a semantic patch request, you must append `domain-model=launchdarkly.semanticpatch` to your `Content-Type` header. To learn more, read [Updates using semantic patch](/reference#updates-using-semantic-patch).
 *
 * The body of a semantic patch request for updating segments requires an `environmentKey` in addition to `instructions` and an optional `comment`. The body of the request takes the following properties:
 *
 * * `comment` (string): (Optional) A description of the update.
 * * `environmentKey` (string): (Required) The key of the LaunchDarkly environment.
 * * `instructions` (array): (Required) A list of actions the update should perform. Each action in the list must be an object with a `kind` property that indicates the instruction. If the action requires parameters, you must include those parameters as additional fields in the object.
 *
 * ### Instructions
 *
 * Semantic patch requests support the following `kind` instructions for updating segments.
 *
 * <details>
 * <summary>Click to expand instructions for <strong>updating segments</strong></summary>
 *
 * #### addIncludedTargets
 *
 * Adds context keys to the individual context targets included in the segment for the specified `contextKind`. Returns an error if this causes the same context key to be both included and excluded.
 *
 * ##### Parameters
 *
 * - `contextKind`: The context kind the targets should be added to.
 * - `values`: List of keys.
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "addIncludedTargets",
 *     "contextKind": "org",
 *     "values": [ "org-key-123abc", "org-key-456def" ]
 *   }]
 * }
 * ```
 *
 * #### addIncludedUsers
 *
 * Adds user keys to the individual user targets included in the segment. Returns an error if this causes the same user key to be both included and excluded. If you are working with contexts, use `addIncludedTargets` instead of this instruction.
 *
 * ##### Parameters
 *
 * - `values`: List of user keys.
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "addIncludedUsers",
 *     "values": [ "user-key-123abc", "user-key-456def" ]
 *   }]
 * }
 * ```
 *
 * #### addExcludedTargets
 *
 * Adds context keys to the individual context targets excluded in the segment for the specified `contextKind`. Returns an error if this causes the same context key to be both included and excluded.
 *
 * ##### Parameters
 *
 * - `contextKind`: The context kind the targets should be added to.
 * - `values`: List of keys.
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "addExcludedTargets",
 *     "contextKind": "org",
 *     "values": [ "org-key-123abc", "org-key-456def" ]
 *   }]
 * }
 * ```
 *
 * #### addExcludedUsers
 *
 * Adds user keys to the individual user targets excluded from the segment. Returns an error if this causes the same user key to be both included and excluded. If you are working with contexts, use `addExcludedTargets` instead of this instruction.
 *
 * ##### Parameters
 *
 * - `values`: List of user keys.
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "addExcludedUsers",
 *     "values": [ "user-key-123abc", "user-key-456def" ]
 *   }]
 * }
 * ```
 *
 * #### removeIncludedTargets
 *
 * Removes context keys from the individual context targets included in the segment for the specified `contextKind`.
 *
 * ##### Parameters
 *
 * - `contextKind`: The context kind the targets should be removed from.
 * - `values`: List of keys.
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "removeIncludedTargets",
 *     "contextKind": "org",
 *     "values": [ "org-key-123abc", "org-key-456def" ]
 *   }]
 * }
 * ```
 *
 * #### removeIncludedUsers
 *
 * Removes user keys from the individual user targets included in the segment. If you are working with contexts, use `removeIncludedTargets` instead of this instruction.
 *
 * ##### Parameters
 *
 * - `values`: List of user keys.
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "removeIncludedUsers",
 *     "values": [ "user-key-123abc", "user-key-456def" ]
 *   }]
 * }
 * ```
 *
 * #### removeExcludedTargets
 *
 * Removes context keys from the individual context targets excluded from the segment for the specified `contextKind`.
 *
 * ##### Parameters
 *
 * - `contextKind`: The context kind the targets should be removed from.
 * - `values`: List of keys.
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "removeExcludedTargets",
 *     "contextKind": "org",
 *     "values": [ "org-key-123abc", "org-key-456def" ]
 *   }]
 * }
 * ```
 *
 * #### removeExcludedUsers
 *
 * Removes user keys from the individual user targets excluded from the segment. If you are working with contexts, use `removeExcludedTargets` instead of this instruction.
 *
 * ##### Parameters
 *
 * - `values`: List of user keys.
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "removeExcludedUsers",
 *     "values": [ "user-key-123abc", "user-key-456def" ]
 *   }]
 * }
 * ```
 *
 * #### updateName
 *
 * Updates the name of the segment.
 *
 * ##### Parameters
 *
 * - `value`: Name of the segment.
 *
 * Here's an example:
 *
 * ```json
 * {
 *   "instructions": [{
 *     "kind": "updateName",
 *     "value": "Updated segment name"
 *   }]
 * }
 * ```
 *
 * </details>
 *
 * ## Using JSON patches on a segment
 *
 * If you do not include the header described above, you can use a [JSON patch](/reference#updates-using-json-patch) or [JSON merge patch](https://datatracker.ietf.org/doc/html/rfc7386) representation of the desired changes.
 *
 * For example, to update the description for a segment with a JSON patch, use the following request body:
 *
 * ```json
 * {
 *   "patch": [
 *     {
 *       "op": "replace",
 *       "path": "/description",
 *       "value": "new description"
 *     }
 *   ]
 * }
 * ```
 *
 * To update fields in the segment that are arrays, set the `path` to the name of the field and then append `/<array index>`. Use `/0` to add the new entry to the beginning of the array. Use `/-` to add the new entry to the end of the array.
 *
 * For example, to add a rule to a segment, use the following request body:
 *
 * ```json
 * {
 *   "patch":[
 *     {
 *       "op": "add",
 *       "path": "/rules/0",
 *       "value": {
 *         "clauses": [{ "contextKind": "user", "attribute": "email", "op": "endsWith", "values": [".edu"], "negate": false }]
 *       }
 *     }
 *   ]
 * }
 * ```
 *
 * To add or remove targets from segments, we recommend using semantic patch. Semantic patch for segments includes specific instructions for adding and removing both included and excluded targets.
 *
 */
export type patchSegment = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: patchSegment_Path;
    headers: patchSegment_Headers;
    cookie: never;
    body: PatchWithComment;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UserSegment;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InvalidRequestErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      409: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: StatusConflictErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Delete a segment.
 */
export type deleteSegment = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: deleteSegment_Path;
    headers: deleteSegment_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      409: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: StatusConflictErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type getSegment_Path = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The segment key
   */
  segmentKey: string;
};

export type getSegment_Headers = { Authorization: string };

export type patchSegment_Path = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The segment key
   */
  segmentKey: string;
};

export type patchSegment_Headers = { Authorization: string };

export type deleteSegment_Path = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The segment key
   */
  segmentKey: string;
};

export type deleteSegment_Headers = { Authorization: string };
