// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../../../../../counterfact-types/index.ts";
import type { ValuePut } from "../../../../../../../../../../../components/schemas/ValuePut.js";
import type { InvalidRequestErrorRep } from "../../../../../../../../../../../components/schemas/InvalidRequestErrorRep.js";
import type { UnauthorizedErrorRep } from "../../../../../../../../../../../components/schemas/UnauthorizedErrorRep.js";
import type { ForbiddenErrorRep } from "../../../../../../../../../../../components/schemas/ForbiddenErrorRep.js";
import type { NotFoundErrorRep } from "../../../../../../../../../../../components/schemas/NotFoundErrorRep.js";
import type { RateLimitedErrorRep } from "../../../../../../../../../../../components/schemas/RateLimitedErrorRep.js";

/**
 *
 * Enable or disable a feature flag for a context based on its context kind and key.
 *
 * Omitting the `setting` attribute from the request body, or including a `setting` of `null`, erases the current setting for a context.
 *
 * If you previously patched the flag, and the patch included the context's data, LaunchDarkly continues to use that data. If LaunchDarkly has never encountered the combination of the context's key and kind before, it calculates the flag values based on the context kind and key.
 *
 */
export type putContextFlagSetting = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: putContextFlagSetting_Path;
    headers: putContextFlagSetting_Headers;
    cookie: never;
    body: ValuePut;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InvalidRequestErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type putContextFlagSetting_Path = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The context kind
   */
  contextKind: string;
  /**
   * The context key
   */
  contextKey: string;
  /**
   * The feature flag key
   */
  featureFlagKey: string;
};

export type putContextFlagSetting_Headers = { Authorization: string };
