// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { forbidden } from "../../../../../../#/components/responses/forbidden.js";
import type { not_found } from "../../../../../../#/components/responses/not_found.js";
import type { gone } from "../../../../../../#/components/responses/gone.js";
import type { validation_failed } from "../../../../../../#/components/responses/validation_failed.js";

/**
 * Users with push access can lock an issue or pull request's conversation.
 *
 * Note that, if you choose not to pass any parameters, you'll need to set `Content-Length` to zero when calling out to this endpoint. For more information, see "[HTTP method](https://docs.github.com/rest/guides/getting-started-with-the-rest-api#http-method)."
 */
export type issuesLock = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: issuesLock_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * The reason for locking the issue or pull request conversation. Lock will fail if you don't use one of these reasons:
       *  * `off-topic`
       *  * `too heated`
       *  * `resolved`
       *  * `spam`
       */
      lock_reason?: "off-topic" | "too heated" | "resolved" | "spam";
    };
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      403: forbidden;
      404: not_found;
      410: gone;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Users with push access can unlock an issue's conversation.
 */
export type issuesUnlock = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: issuesUnlock_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      403: forbidden;
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type issuesLock_Path = {
  owner: string;
  repo: string;
  issue_number: number;
};

export type issuesUnlock_Path = {
  owner: string;
  repo: string;
  issue_number: number;
};
