// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { alert_number } from "../../../../../../../components/schemas/alert-number.js";
import type { code_scanning_autofix } from "../../../../../../../components/schemas/code-scanning-autofix.js";
import type { code_scanning_bad_request } from "../../../../../../../#/components/responses/code_scanning_bad_request.js";
import type { code_scanning_forbidden_read } from "../../../../../../../#/components/responses/code_scanning_forbidden_read.js";
import type { not_found } from "../../../../../../../#/components/responses/not_found.js";
import type { service_unavailable } from "../../../../../../../#/components/responses/service_unavailable.js";
import type { code_scanning_autofix_create_forbidden } from "../../../../../../../#/components/responses/code_scanning_autofix_create_forbidden.js";

/**
 * Gets the status and description of an autofix for a code scanning alert on the repository's default branch.
 *
 * OAuth app tokens and personal access tokens (classic) need the `security_events` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use this endpoint with only public repositories.
 */
export type codeScanningGetAutofix = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: codeScanningGetAutofix_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: code_scanning_autofix;
          };
        };
        examples: {
          default: unknown;
        };
      };
      400: code_scanning_bad_request;
      403: code_scanning_forbidden_read;
      404: not_found;
      503: service_unavailable;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Creates an autofix for a code scanning alert.
 *
 * If a new autofix is to be created as a result of this request or is currently being generated, then this endpoint will return a 202 Accepted response.
 *
 * If an autofix already exists for a given alert, then this endpoint will return a 200 OK response.
 *
 * OAuth app tokens and personal access tokens (classic) need the `security_events` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use this endpoint with only public repositories.
 */
export type codeScanningCreateAutofix = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: codeScanningCreateAutofix_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: code_scanning_autofix;
          };
        };
        examples: {
          default: unknown;
        };
      };
      202: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: code_scanning_autofix;
          };
        };
        examples: {
          default: unknown;
        };
      };
      400: code_scanning_bad_request;
      403: code_scanning_autofix_create_forbidden;
      404: not_found;
      422: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      503: service_unavailable;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type codeScanningGetAutofix_Path = {
  owner: string;
  repo: string;
  alert_number: alert_number;
};

export type codeScanningCreateAutofix_Path = {
  owner: string;
  repo: string;
  alert_number: alert_number;
};
