// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { code_scanning_ref } from "../../../../../../../components/schemas/code-scanning-ref.js";
import type { alert_number } from "../../../../../../../components/schemas/alert-number.js";
import type { code_scanning_alert_instance_list } from "../../../../../../../components/schemas/code-scanning-alert-instance-list.js";
import type { code_scanning_forbidden_read } from "../../../../../../../#/components/responses/code_scanning_forbidden_read.js";
import type { not_found } from "../../../../../../../#/components/responses/not_found.js";
import type { service_unavailable } from "../../../../../../../#/components/responses/service_unavailable.js";

/**
 * Lists all instances of the specified code scanning alert.
 *
 * OAuth app tokens and personal access tokens (classic) need the `security_events` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use this endpoint with only public repositories.
 */
export type codeScanningListAlertInstances = (
  $: OmitValueWhenNever<{
    query: codeScanningListAlertInstances_Query;
    querystring: never;
    path: codeScanningListAlertInstances_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<code_scanning_alert_instance_list>;
          };
        };
        examples: {
          default: unknown;
        };
      };
      403: code_scanning_forbidden_read;
      404: not_found;
      503: service_unavailable;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type codeScanningListAlertInstances_Query = {
  page?: number;
  per_page?: number;
  ref?: code_scanning_ref;
  pr?: number;
};

export type codeScanningListAlertInstances_Path = {
  owner: string;
  repo: string;
  alert_number: alert_number;
};
