// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../counterfact-types/index.ts";
import type { Context } from "../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../counterfact-types/index.ts";
import type { codespace } from "../../components/schemas/codespace.js";
import type { not_modified } from "../../#/components/responses/not_modified.js";
import type { requires_authentication } from "../../#/components/responses/requires_authentication.js";
import type { forbidden } from "../../#/components/responses/forbidden.js";
import type { not_found } from "../../#/components/responses/not_found.js";
import type { internal_error } from "../../#/components/responses/internal_error.js";
import type { service_unavailable } from "../../#/components/responses/service_unavailable.js";

/**
 * Lists the authenticated user's codespaces.
 *
 * OAuth app tokens and personal access tokens (classic) need the `codespace` scope to use this endpoint.
 */
export type codespacesListForAuthenticatedUser = (
  $: OmitValueWhenNever<{
    query: codespacesListForAuthenticatedUser_Query;
    querystring: never;
    path: never;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: { total_count: number; codespaces: Array<codespace> };
          };
        };
        examples: {
          default: unknown;
        };
      };
      304: not_modified;
      401: requires_authentication;
      403: forbidden;
      404: not_found;
      500: internal_error;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Creates a new codespace, owned by the authenticated user.
 *
 * This endpoint requires either a `repository_id` OR a `pull_request` but not both.
 *
 * OAuth app tokens and personal access tokens (classic) need the `codespace` scope to use this endpoint.
 */
export type codespacesCreateForAuthenticatedUser = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: never;
    headers: never;
    cookie: never;
    body:
      | {
          /**
           * Repository id for this codespace
           */
          repository_id: number;
          /**
           * Git ref (typically a branch name) for this codespace
           */
          ref?: string;
          /**
           * The requested location for a new codespace. Best efforts are made to respect this upon creation. Assigned by IP if not provided.
           */
          location?: string;
          /**
           * The geographic area for this codespace. If not specified, the value is assigned by IP. This property replaces `location`, which is closing down.
           */
          geo?: "EuropeWest" | "SoutheastAsia" | "UsEast" | "UsWest";
          /**
           * IP for location auto-detection when proxying a request
           */
          client_ip?: string;
          /**
           * Machine type to use for this codespace
           */
          machine?: string;
          /**
           * Path to devcontainer.json config to use for this codespace
           */
          devcontainer_path?: string;
          /**
           * Whether to authorize requested permissions from devcontainer.json
           */
          multi_repo_permissions_opt_out?: boolean;
          /**
           * Working directory for this codespace
           */
          working_directory?: string;
          /**
           * Time in minutes before codespace stops from inactivity
           */
          idle_timeout_minutes?: number;
          /**
           * Display name for this codespace
           */
          display_name?: string;
          /**
           * Duration in minutes after codespace has gone idle in which it will be deleted. Must be integer minutes between 0 and 43200 (30 days).
           */
          retention_period_minutes?: number;
        }
      | {
          /**
           * Pull request number for this codespace
           */
          pull_request: {
            /**
             * Pull request number
             */
            pull_request_number: number;
            /**
             * Repository id for this codespace
             */
            repository_id: number;
          };
          /**
           * The requested location for a new codespace. Best efforts are made to respect this upon creation. Assigned by IP if not provided.
           */
          location?: string;
          /**
           * The geographic area for this codespace. If not specified, the value is assigned by IP. This property replaces `location`, which is closing down.
           */
          geo?: "EuropeWest" | "SoutheastAsia" | "UsEast" | "UsWest";
          /**
           * Machine type to use for this codespace
           */
          machine?: string;
          /**
           * Path to devcontainer.json config to use for this codespace
           */
          devcontainer_path?: string;
          /**
           * Working directory for this codespace
           */
          working_directory?: string;
          /**
           * Time in minutes before codespace stops from inactivity
           */
          idle_timeout_minutes?: number;
        };
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: codespace;
          };
        };
        examples: {
          default: unknown;
        };
      };
      202: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: codespace;
          };
        };
        examples: {
          default: unknown;
        };
      };
      401: requires_authentication;
      403: forbidden;
      404: not_found;
      503: service_unavailable;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type codespacesListForAuthenticatedUser_Query = {
  per_page?: number;
  page?: number;
  repository_id?: number;
};
