// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../counterfact-types/index.ts";
import type { Context } from "../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../counterfact-types/index.ts";
import type { installation } from "../../components/schemas/installation.js";
import type { not_modified } from "../../#/components/responses/not_modified.js";
import type { requires_authentication } from "../../#/components/responses/requires_authentication.js";
import type { forbidden } from "../../#/components/responses/forbidden.js";

/**
 * Lists installations of your GitHub App that the authenticated user has explicit permission (`:read`, `:write`, or `:admin`) to access.
 *
 * The authenticated user has explicit permission to access repositories they own, repositories where they are a collaborator, and repositories that they can access through an organization membership.
 *
 * You can find the permissions for the installation under the `permissions` key.
 */
export type appsListInstallationsForAuthenticatedUser = (
  $: OmitValueWhenNever<{
    query: appsListInstallationsForAuthenticatedUser_Query;
    querystring: never;
    path: never;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: { total_count: number; installations: Array<installation> };
          };
        };
        examples: {
          default: unknown;
        };
      };
      304: not_modified;
      401: requires_authentication;
      403: forbidden;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type appsListInstallationsForAuthenticatedUser_Query = {
  per_page?: number;
  page?: number;
};
