// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../counterfact-types/index.ts";
import type { Context } from "../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../counterfact-types/index.ts";
import type { migration } from "../../components/schemas/migration.js";
import type { not_modified } from "../../#/components/responses/not_modified.js";
import type { requires_authentication } from "../../#/components/responses/requires_authentication.js";
import type { forbidden } from "../../#/components/responses/forbidden.js";
import type { validation_failed } from "../../#/components/responses/validation_failed.js";

/**
 * Lists all migrations a user has started.
 */
export type migrationsListForAuthenticatedUser = (
  $: OmitValueWhenNever<{
    query: migrationsListForAuthenticatedUser_Query;
    querystring: never;
    path: never;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<migration>;
          };
        };
        examples: {
          default: unknown;
        };
      };
      304: not_modified;
      401: requires_authentication;
      403: forbidden;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Initiates the generation of a user migration archive.
 */
export type migrationsStartForAuthenticatedUser = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: never;
    headers: never;
    cookie: never;
    body: {
      /**
       * Lock the repositories being migrated at the start of the migration
       * @example true
       */
      lock_repositories?: boolean;
      /**
       * Indicates whether metadata should be excluded and only git source should be included for the migration.
       * @example true
       */
      exclude_metadata?: boolean;
      /**
       * Indicates whether the repository git data should be excluded from the migration.
       * @example true
       */
      exclude_git_data?: boolean;
      /**
       * Do not include attachments in the migration
       * @example true
       */
      exclude_attachments?: boolean;
      /**
       * Do not include releases in the migration
       * @example true
       */
      exclude_releases?: boolean;
      /**
       * Indicates whether projects owned by the organization or users should be excluded.
       * @example true
       */
      exclude_owner_projects?: boolean;
      /**
       * Indicates whether this should only include organization metadata (repositories array should be empty and will ignore other flags).
       * @default false
       * @example true
       */
      org_metadata_only?: boolean;
      /**
       * Exclude attributes from the API response to improve performance
       * @example ["repositories"]
       */
      exclude?: Array<"repositories">;
      repositories: Array<string>;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: migration;
          };
        };
        examples: {
          default: unknown;
        };
      };
      304: not_modified;
      401: requires_authentication;
      403: forbidden;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type migrationsListForAuthenticatedUser_Query = {
  per_page?: number;
  page?: number;
};
