// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { deployment_status } from "../../../../../../components/schemas/deployment-status.js";
import type { not_found } from "../../../../../../#/components/responses/not_found.js";
import type { validation_failed } from "../../../../../../#/components/responses/validation_failed.js";

/**
 * Users with pull access can view deployment statuses for a deployment:
 */
export type reposListDeploymentStatuses = (
  $: OmitValueWhenNever<{
    query: reposListDeploymentStatuses_Query;
    querystring: never;
    path: reposListDeploymentStatuses_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<deployment_status>;
          };
        };
        examples: {
          default: unknown;
        };
      };
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Users with `push` access can create deployment statuses for a given deployment.
 *
 * OAuth app tokens and personal access tokens (classic) need the `repo_deployment` scope to use this endpoint.
 */
export type reposCreateDeploymentStatus = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: reposCreateDeploymentStatus_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * The state of the status. When you set a transient deployment to `inactive`, the deployment will be shown as `destroyed` in GitHub.
       */
      state:
        | "error"
        | "failure"
        | "inactive"
        | "in_progress"
        | "queued"
        | "pending"
        | "success";
      /**
       * The target URL to associate with this status. This URL should contain output to keep the user updated while the task is running or serve as historical information for what happened in the deployment.
       *
       * > [!NOTE]
       * > It's recommended to use the `log_url` parameter, which replaces `target_url`.
       * @default ""
       */
      target_url?: string;
      /**
       * The full URL of the deployment's output. This parameter replaces `target_url`. We will continue to accept `target_url` to support legacy uses, but we recommend replacing `target_url` with `log_url`. Setting `log_url` will automatically set `target_url` to the same value. Default: `""`
       * @default ""
       */
      log_url?: string;
      /**
       * A short description of the status. The maximum description length is 140 characters.
       * @default ""
       */
      description?: string;
      /**
       * Name for the target deployment environment, which can be changed when setting a deploy status. For example, `production`, `staging`, or `qa`. If not defined, the environment of the previous status on the deployment will be used, if it exists. Otherwise, the environment of the deployment will be used.
       */
      environment?: string;
      /**
       * Sets the URL for accessing your environment. Default: `""`
       * @default ""
       */
      environment_url?: string;
      /**
       * Adds a new `inactive` status to all prior non-transient, non-production environment deployments with the same repository and `environment` name as the created status's deployment. An `inactive` status is only added to deployments that had a `success` state. Default: `true`
       */
      auto_inactive?: boolean;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: {
          Location: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: deployment_status;
          };
        };
        examples: {
          default: unknown;
        };
      };
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type reposListDeploymentStatuses_Query = {
  per_page?: number;
  page?: number;
};

export type reposListDeploymentStatuses_Path = {
  owner: string;
  repo: string;
  deployment_id: number;
};

export type reposCreateDeploymentStatus_Path = {
  owner: string;
  repo: string;
  deployment_id: number;
};
