// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { minimal_repository } from "../../../../../../components/schemas/minimal-repository.js";

/**
 * Lists all repositories that have been selected when the `visibility`
 * for repository access to a secret is set to `selected`.
 *
 * Authenticated users must have collaborator access to a repository to create, update, or read secrets.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint. If the repository is private, the `repo` scope is also required.
 */
export type actionsListSelectedReposForOrgSecret = (
  $: OmitValueWhenNever<{
    query: actionsListSelectedReposForOrgSecret_Query;
    querystring: never;
    path: actionsListSelectedReposForOrgSecret_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              total_count: number;
              repositories: Array<minimal_repository>;
            };
          };
        };
        examples: {
          default: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Replaces all repositories for an organization secret when the `visibility`
 * for repository access is set to `selected`. The visibility is set when you [Create
 * or update an organization secret](https://docs.github.com/rest/actions/secrets#create-or-update-an-organization-secret).
 *
 * Authenticated users must have collaborator access to a repository to create, update, or read secrets.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint. If the repository is private, the `repo` scope is also required.
 */
export type actionsSetSelectedReposForOrgSecret = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: actionsSetSelectedReposForOrgSecret_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * An array of repository ids that can access the organization secret. You can only provide a list of repository ids when the `visibility` is set to `selected`. You can add and remove individual repositories using the [Add selected repository to an organization secret](https://docs.github.com/rest/actions/secrets#add-selected-repository-to-an-organization-secret) and [Remove selected repository from an organization secret](https://docs.github.com/rest/actions/secrets#remove-selected-repository-from-an-organization-secret) endpoints.
       */
      selected_repository_ids: Array<number>;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type actionsListSelectedReposForOrgSecret_Query = {
  page?: number;
  per_page?: number;
};

export type actionsListSelectedReposForOrgSecret_Path = {
  org: string;
  secret_name: string;
};

export type actionsSetSelectedReposForOrgSecret_Path = {
  org: string;
  secret_name: string;
};
