// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { copilot_space_resource } from "../../../../../../components/schemas/copilot-space-resource.js";
import type { forbidden } from "../../../../../../#/components/responses/forbidden.js";
import type { not_found } from "../../../../../../#/components/responses/not_found.js";
import type { validation_failed } from "../../../../../../#/components/responses/validation_failed.js";

/**
 * Gets a specific resource attached to a Copilot Space owned by a user.
 * The authenticated user must have appropriate permissions to view the space.
 *
 * OAuth app tokens and personal access tokens (classic) need the `read:user` scope to use this endpoint.
 */
export type copilotSpacesGetResourceForUser = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: copilotSpacesGetResourceForUser_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: copilot_space_resource;
          };
        };
        examples: {
          default: unknown;
        };
      };
      403: forbidden;
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Updates the metadata of a resource in a specific Copilot Space owned by a user.
 * The authenticated user must have write permissions on the space.
 *
 * OAuth app tokens and personal access tokens (classic) need the `write:user` scope to use this endpoint.
 */
export type copilotSpacesUpdateResourceForUser = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: copilotSpacesUpdateResourceForUser_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * Updated resource-specific metadata.
       */
      metadata?: { [key: string]: unknown };
    };
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: copilot_space_resource;
          };
        };
        examples: {
          default: unknown;
        };
      };
      403: forbidden;
      404: not_found;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Deletes a resource from a specific Copilot Space owned by a user.
 * The authenticated user must have write permissions on the space.
 *
 * OAuth app tokens and personal access tokens (classic) need the `write:user` scope to use this endpoint.
 */
export type copilotSpacesDeleteResourceForUser = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: copilotSpacesDeleteResourceForUser_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      403: forbidden;
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type copilotSpacesGetResourceForUser_Path = {
  username: string;
  /**
   * The unique identifier of the Copilot Space.
   */
  space_number: number;
  /**
   * The unique identifier of the resource.
   */
  space_resource_id: number;
};

export type copilotSpacesUpdateResourceForUser_Path = {
  username: string;
  /**
   * The unique identifier of the Copilot Space.
   */
  space_number: number;
  /**
   * The unique identifier of the resource.
   */
  space_resource_id: number;
};

export type copilotSpacesDeleteResourceForUser_Path = {
  username: string;
  /**
   * The unique identifier of the Copilot Space.
   */
  space_number: number;
  /**
   * The unique identifier of the resource.
   */
  space_resource_id: number;
};
