export type secret_scanning_pattern_override = {
  /**
   * The ID of the pattern.
   */
  token_type?: string;
  /**
   * The version of this pattern if it's a custom pattern.
   */
  custom_pattern_version?: string;
  /**
   * The slug of the pattern.
   */
  slug?: string;
  /**
   * The user-friendly name for the pattern.
   */
  display_name?: string;
  /**
   * The total number of alerts generated by this pattern.
   */
  alert_total?: number;
  /**
   * The percentage of all alerts that this pattern represents, rounded to the nearest integer.
   */
  alert_total_percentage?: number;
  /**
   * The number of false positive alerts generated by this pattern.
   */
  false_positives?: number;
  /**
   * The percentage of alerts from this pattern that are false positives, rounded to the nearest integer.
   */
  false_positive_rate?: number;
  /**
   * The percentage of blocks for this pattern that were bypassed, rounded to the nearest integer.
   */
  bypass_rate?: number;
  /**
   * The default push protection setting for this pattern.
   */
  default_setting?: "disabled" | "enabled";
  /**
   * The push protection setting for this pattern set at the enterprise level. Only present for partner patterns when the organization has a parent enterprise.
   */
  enterprise_setting?: "not-set" | "disabled" | "enabled";
  /**
   * The current push protection setting for this pattern. If this is `not-set`, then it inherits either the enterprise setting if it exists or the default setting.
   */
  setting?: "not-set" | "disabled" | "enabled";
};
