// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { repository_collaborator_permission } from "../../../../../../components/schemas/repository-collaborator-permission.js";
import type { not_found } from "../../../../../../#/components/responses/not_found.js";

/**
 * Checks the repository permission and role of a collaborator.
 *
 * The `permission` attribute provides the legacy base roles of `admin`, `write`, `read`, and `none`, where the
 * `maintain` role is mapped to `write` and the `triage` role is mapped to `read`.
 * The `role_name` attribute provides the name of the assigned role, including custom roles. The
 * `permission` can also be used to determine which base level of access the collaborator has to the repository.
 *
 * The calculated permissions are the highest role assigned to the collaborator after considering all sources of grants, including: repo, teams, organization, and enterprise.
 * There is presently not a way to differentiate between an organization level grant and a repository level grant from this endpoint response.
 */
export type reposGetCollaboratorPermissionLevel = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: reposGetCollaboratorPermissionLevel_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: repository_collaborator_permission;
          };
        };
        examples: {
          "response-if-user-has-admin-permissions": unknown;
        };
      };
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type reposGetCollaboratorPermissionLevel_Path = {
  owner: string;
  repo: string;
  username: string;
};
