// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { forbidden } from "../../../../../../../#/components/responses/forbidden.js";
import type { not_found } from "../../../../../../../#/components/responses/not_found.js";
import type { conflict } from "../../../../../../../#/components/responses/conflict.js";
import type { validation_failed } from "../../../../../../../#/components/responses/validation_failed.js";

/**
 * Adds a repository to the list of repositories that are allowed to use self-hosted runners in an organization.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope or the "Actions policies" fine-grained permission to use this endpoint.
 */
export type actionsEnableSelectedRepositorySelfHostedRunnersOrganization = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: actionsEnableSelectedRepositorySelfHostedRunnersOrganization_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      403: forbidden;
      404: not_found;
      409: conflict;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Removes a repository from the list of repositories that are allowed to use self-hosted runners in an organization.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope or the "Actions policies" fine-grained permission to use this endpoint.
 */
export type actionsDisableSelectedRepositorySelfHostedRunnersOrganization = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: actionsDisableSelectedRepositorySelfHostedRunnersOrganization_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      403: forbidden;
      404: not_found;
      409: conflict;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type actionsEnableSelectedRepositorySelfHostedRunnersOrganization_Path =
  { org: string; repository_id: number };

export type actionsDisableSelectedRepositorySelfHostedRunnersOrganization_Path =
  { org: string; repository_id: number };
