// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { page_deployment } from "../../../../../components/schemas/page-deployment.js";
import type { bad_request } from "../../../../../#/components/responses/bad_request.js";
import type { not_found } from "../../../../../#/components/responses/not_found.js";
import type { validation_failed } from "../../../../../#/components/responses/validation_failed.js";

/**
 * Create a GitHub Pages deployment for a repository.
 *
 * The authenticated user must have write permission to the repository.
 */
export type reposCreatePagesDeployment = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: reposCreatePagesDeployment_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * The ID of an artifact that contains the .zip or .tar of static assets to deploy. The artifact belongs to the repository. Either `artifact_id` or `artifact_url` are required.
       */
      artifact_id?: number;
      /**
       * The URL of an artifact that contains the .zip or .tar of static assets to deploy. The artifact belongs to the repository. Either `artifact_id` or `artifact_url` are required.
       */
      artifact_url?: string;
      /**
       * The target environment for this GitHub Pages deployment.
       * @default "github-pages"
       */
      environment?: string;
      /**
       * A unique string that represents the version of the build for this deployment.
       * @default "GITHUB_SHA"
       */
      pages_build_version: string;
      /**
       * The OIDC token issued by GitHub Actions certifying the origin of the deployment.
       */
      oidc_token: string;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: page_deployment;
          };
        };
        examples: {
          default: unknown;
        };
      };
      400: bad_request;
      404: not_found;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type reposCreatePagesDeployment_Path = { owner: string; repo: string };
