// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { deploy_key } from "../../../../components/schemas/deploy-key.js";
import type { validation_failed } from "../../../../#/components/responses/validation_failed.js";

export type reposListDeployKeys = (
  $: OmitValueWhenNever<{
    query: reposListDeployKeys_Query;
    querystring: never;
    path: reposListDeployKeys_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<deploy_key>;
          };
        };
        examples: {
          default: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * You can create a read-only deploy key.
 */
export type reposCreateDeployKey = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: reposCreateDeployKey_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * A name for the key.
       */
      title?: string;
      /**
       * The contents of the key.
       */
      key: string;
      /**
       * If `true`, the key will only be able to read repository contents. Otherwise, the key will be able to read and write.
       *
       * Deploy keys with write access can perform the same actions as an organization member with admin access, or a collaborator on a personal repository. For more information, see "[Repository permission levels for an organization](https://docs.github.com/articles/repository-permission-levels-for-an-organization/)" and "[Permission levels for a user account repository](https://docs.github.com/articles/permission-levels-for-a-user-account-repository/)."
       */
      read_only?: boolean;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: {
          Location: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: deploy_key;
          };
        };
        examples: {
          default: unknown;
        };
      };
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type reposListDeployKeys_Query = { per_page?: number; page?: number };

export type reposListDeployKeys_Path = { owner: string; repo: string };

export type reposCreateDeployKey_Path = { owner: string; repo: string };
