// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { PullRequestCollectionRep } from "../../../../components/schemas/PullRequestCollectionRep.js";
import type { ValidationFailedErrorRep } from "../../../../components/schemas/ValidationFailedErrorRep.js";
import type { UnauthorizedErrorRep } from "../../../../components/schemas/UnauthorizedErrorRep.js";
import type { ForbiddenErrorRep } from "../../../../components/schemas/ForbiddenErrorRep.js";
import type { NotFoundErrorRep } from "../../../../components/schemas/NotFoundErrorRep.js";
import type { RateLimitedErrorRep } from "../../../../components/schemas/RateLimitedErrorRep.js";

/**
 * Get a list of pull requests
 *
 * ### Expanding the pull request collection response
 *
 * LaunchDarkly supports expanding the pull request collection response to include additional fields.
 *
 * To expand the response, append the `expand` query parameter and include the following:
 *
 * * `deployments` includes details on all of the deployments associated with each pull request
 * * `flagReferences` includes details on all of the references to flags in each pull request
 * * `leadTime` includes details about the lead time of the pull request for each stage
 *
 * For example, use `?expand=deployments` to include the `deployments` field in the response. By default, this field is **not** included in the response.
 *
 */
export type getPullRequests = (
  $: OmitValueWhenNever<{
    query: getPullRequests_Query;
    querystring: never;
    path: never;
    headers: getPullRequests_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: PullRequestCollectionRep;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ValidationFailedErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type getPullRequests_Query = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * Required if you are using the <code>sort</code> parameter's <code>leadTime</code> option to sort pull requests.
   */
  environmentKey?: string;
  /**
   * Filter the results to pull requests deployed to a comma separated list of applications
   */
  applicationKey?: string;
  /**
   * Filter results to pull requests with the given status. Options: `open`, `merged`, `closed`, `deployed`.
   */
  status?: string;
  /**
   * Filter list of pull requests by title or author
   */
  query?: string;
  /**
   * The number of pull requests to return. Default is 20. Maximum allowed is 100.
   */
  limit?: number;
  /**
   * Expand properties in response. Options: `deployments`, `flagReferences`, `leadTime`.
   */
  expand?: string;
  /**
   * Sort results. Requires the `environmentKey` to be set. Options: `leadTime` (asc) and `-leadTime` (desc). When query option is excluded, default sort is by created or merged date.
   */
  sort?: string;
  /**
   * Unix timestamp in milliseconds. Default value is 7 days ago.
   */
  from?: string;
  /**
   * Unix timestamp in milliseconds. Default value is now.
   */
  to?: string;
  /**
   * Identifier used for pagination
   */
  after?: string;
  /**
   * Identifier used for pagination
   */
  before?: string;
};

export type getPullRequests_Headers = { Authorization: string };
