// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { branch_protection } from "../../../../../../components/schemas/branch-protection.js";
import type { not_found } from "../../../../../../#/components/responses/not_found.js";
import type { protected_branch } from "../../../../../../components/schemas/protected-branch.js";
import type { forbidden } from "../../../../../../#/components/responses/forbidden.js";
import type { validation_failed_simple } from "../../../../../../#/components/responses/validation_failed_simple.js";

/**
 * Protected branches are available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see [GitHub's products](https://docs.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation.
 */
export type reposGetBranchProtection = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: reposGetBranchProtection_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: branch_protection;
          };
        };
        examples: {
          default: unknown;
        };
      };
      404: not_found;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Protected branches are available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see [GitHub's products](https://docs.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation.
 *
 * Protecting a branch requires admin or owner permissions to the repository.
 *
 * > [!NOTE]
 * > Passing new arrays of `users` and `teams` replaces their previous values.
 *
 * > [!NOTE]
 * > The list of users, apps, and teams in total is limited to 100 items.
 */
export type reposUpdateBranchProtection = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: reposUpdateBranchProtection_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * Require status checks to pass before merging. Set to `null` to disable.
       */
      required_status_checks: {
        /**
         * Require branches to be up to date before merging.
         */
        strict: boolean;
        /**
         * **Closing down notice**: The list of status checks to require in order to merge into this branch. If any of these checks have recently been set by a particular GitHub App, they will be required to come from that app in future for the branch to merge. Use `checks` instead of `contexts` for more fine-grained control.
         * @deprecated
         */
        contexts: Array<string>;
        /**
         * The list of status checks to require in order to merge into this branch.
         */
        checks?: Array<{
          /**
           * The name of the required check
           */
          context: string;
          /**
           * The ID of the GitHub App that must provide this check. Omit this field to automatically select the GitHub App that has recently provided this check, or any app if it was not set by a GitHub App. Pass -1 to explicitly allow any app to set the status.
           */
          app_id?: number;
        }>;
      };
      /**
       * Enforce all configured restrictions for administrators. Set to `true` to enforce required status checks for repository administrators. Set to `null` to disable.
       */
      enforce_admins: boolean;
      /**
       * Require at least one approving review on a pull request, before merging. Set to `null` to disable.
       */
      required_pull_request_reviews: {
        /**
         * Specify which users, teams, and apps can dismiss pull request reviews. Pass an empty `dismissal_restrictions` object to disable. User and team `dismissal_restrictions` are only available for organization-owned repositories. Omit this parameter for personal repositories.
         */
        dismissal_restrictions?: {
          /**
           * The list of user `login`s with dismissal access
           */
          users?: Array<string>;
          /**
           * The list of team `slug`s with dismissal access
           */
          teams?: Array<string>;
          /**
           * The list of app `slug`s with dismissal access
           */
          apps?: Array<string>;
        };
        /**
         * Set to `true` if you want to automatically dismiss approving reviews when someone pushes a new commit.
         */
        dismiss_stale_reviews?: boolean;
        /**
         * Blocks merging pull requests until [code owners](https://docs.github.com/articles/about-code-owners/) review them.
         */
        require_code_owner_reviews?: boolean;
        /**
         * Specify the number of reviewers required to approve pull requests. Use a number between 1 and 6 or 0 to not require reviewers.
         */
        required_approving_review_count?: number;
        /**
         * Whether the most recent push must be approved by someone other than the person who pushed it. Default: `false`.
         * @default false
         */
        require_last_push_approval?: boolean;
        /**
         * Allow specific users, teams, or apps to bypass pull request requirements.
         */
        bypass_pull_request_allowances?: {
          /**
           * The list of user `login`s allowed to bypass pull request requirements.
           */
          users?: Array<string>;
          /**
           * The list of team `slug`s allowed to bypass pull request requirements.
           */
          teams?: Array<string>;
          /**
           * The list of app `slug`s allowed to bypass pull request requirements.
           */
          apps?: Array<string>;
        };
      };
      /**
       * Restrict who can push to the protected branch. User, app, and team `restrictions` are only available for organization-owned repositories. Set to `null` to disable.
       */
      restrictions: {
        /**
         * The list of user `login`s with push access
         */
        users: Array<string>;
        /**
         * The list of team `slug`s with push access
         */
        teams: Array<string>;
        /**
         * The list of app `slug`s with push access
         */
        apps?: Array<string>;
      };
      /**
       * Enforces a linear commit Git history, which prevents anyone from pushing merge commits to a branch. Set to `true` to enforce a linear commit history. Set to `false` to disable a linear commit Git history. Your repository must allow squash merging or rebase merging before you can enable a linear commit history. Default: `false`. For more information, see "[Requiring a linear commit history](https://docs.github.com/github/administering-a-repository/requiring-a-linear-commit-history)" in the GitHub Help documentation.
       */
      required_linear_history?: boolean;
      /**
       * Permits force pushes to the protected branch by anyone with write access to the repository. Set to `true` to allow force pushes. Set to `false` or `null` to block force pushes. Default: `false`. For more information, see "[Enabling force pushes to a protected branch](https://docs.github.com/github/administering-a-repository/enabling-force-pushes-to-a-protected-branch)" in the GitHub Help documentation."
       */
      allow_force_pushes?: boolean;
      /**
       * Allows deletion of the protected branch by anyone with write access to the repository. Set to `false` to prevent deletion of the protected branch. Default: `false`. For more information, see "[Enabling force pushes to a protected branch](https://docs.github.com/github/administering-a-repository/enabling-force-pushes-to-a-protected-branch)" in the GitHub Help documentation.
       */
      allow_deletions?: boolean;
      /**
       * If set to `true`, the `restrictions` branch protection settings which limits who can push will also block pushes which create new branches, unless the push is initiated by a user, team, or app which has the ability to push. Set to `true` to restrict new branch creation. Default: `false`.
       */
      block_creations?: boolean;
      /**
       * Requires all conversations on code to be resolved before a pull request can be merged into a branch that matches this rule. Set to `false` to disable. Default: `false`.
       */
      required_conversation_resolution?: boolean;
      /**
       * Whether to set the branch as read-only. If this is true, users will not be able to push to the branch. Default: `false`.
       * @default false
       */
      lock_branch?: boolean;
      /**
       * Whether users can pull changes from upstream when the branch is locked. Set to `true` to allow fork syncing. Set to `false` to prevent fork syncing. Default: `false`.
       * @default false
       */
      allow_fork_syncing?: boolean;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: protected_branch;
          };
        };
        examples: {
          default: unknown;
        };
      };
      403: forbidden;
      404: not_found;
      422: validation_failed_simple;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Protected branches are available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see [GitHub's products](https://docs.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation.
 */
export type reposDeleteBranchProtection = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: reposDeleteBranchProtection_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      403: forbidden;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type reposGetBranchProtection_Path = {
  owner: string;
  repo: string;
  branch: string;
};

export type reposUpdateBranchProtection_Path = {
  owner: string;
  repo: string;
  branch: string;
};

export type reposDeleteBranchProtection_Path = {
  owner: string;
  repo: string;
  branch: string;
};
