// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { hook_delivery } from "../../../../../../../components/schemas/hook-delivery.js";
import type { bad_request } from "../../../../../../../#/components/responses/bad_request.js";
import type { validation_failed } from "../../../../../../../#/components/responses/validation_failed.js";

/**
 * Returns a delivery for a webhook configured in a repository.
 */
export type reposGetWebhookDelivery = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: reposGetWebhookDelivery_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: hook_delivery;
          };
        };
        examples: {
          default: unknown;
        };
      };
      400: bad_request;
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type reposGetWebhookDelivery_Path = {
  owner: string;
  repo: string;
  hook_id: number;
  delivery_id: number;
};
