/**
 * All statuses documented 2026-08-02: 1 UNSENT; 3 REJECTED; 4 CANCELLED; 5 SUCCESS; 6 SEND_NOW; 9 PENDING_BATCH_RESPONSE; 10 PENDING_VERIFICATION; 11 PENDING_PLACEMENT; 12 EXCEPTION_DURING_PLACEMENT_PREPARATION; 13 CONNECTION_ERROR_DURING_PLACEMENT; 14 RESPONSE_PROCESSING_ERROR; 15 GENERIC_ERROR_RESPONSE; 17 MERGED; 18 CREDIT_CARD_RETRY; 19 AWAITING_RETRY_INSTRUCTIONS; 20 AWAITING_RESPONSE_CLASSIFICATION. Source: https://developer.ordergroove.com/reference/order-status-codes
 */
export type OrderStatus =
  | 1
  | 3
  | 4
  | 5
  | 6
  | 9
  | 10
  | 11
  | 12
  | 13
  | 14
  | 15
  | 17
  | 18
  | 19
  | 20;
