// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { actions_hosted_runner } from "../../../../../components/schemas/actions-hosted-runner.js";

/**
 * Gets a GitHub-hosted runner configured in an organization.
 *
 * OAuth app tokens and personal access tokens (classic) need the `manage_runners:org` scope to use this endpoint.
 */
export type actionsGetHostedRunnerForOrg = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: actionsGetHostedRunnerForOrg_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: actions_hosted_runner;
          };
        };
        examples: {
          default: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Updates a GitHub-hosted runner for an organization.
 * OAuth app tokens and personal access tokens (classic) need the `manage_runners:org` scope to use this endpoint.
 */
export type actionsUpdateHostedRunnerForOrg = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: actionsUpdateHostedRunnerForOrg_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * Name of the runner. Must be between 1 and 64 characters and may only contain upper and lowercase letters a-z, numbers 0-9, '.', '-', and '_'.
       */
      name?: string;
      /**
       * The existing runner group to add this runner to.
       */
      runner_group_id?: number;
      /**
       * The maximum amount of runners to scale up to. Runners will not auto-scale above this number. Use this setting to limit your cost.
       */
      maximum_runners?: number;
      /**
       * Whether this runner should be updated with a static public IP. Note limit on account. To list limits on account, use `GET actions/hosted-runners/limits`
       */
      enable_static_ip?: boolean;
      /**
       * The machine size of the runner. To list available sizes, use `GET actions/hosted-runners/machine-sizes`
       */
      size?: string;
      /**
       * The source type of the runner image to use. Must match the source of the image specified by `image_id`. Can be one of `github`, `partner`, or `custom`.
       */
      image_source?: "github" | "partner" | "custom";
      /**
       * The unique identifier of the runner image. To list available images, use `GET /actions/hosted-runners/images/github-owned`, `GET /actions/hosted-runners/images/partner`, or `GET /actions/hosted-runners/images/custom`.
       */
      image_id?: string;
      /**
       * The version of the runner image to deploy. This is relevant only for runners using custom images.
       */
      image_version?: string;
      /**
       * Whether to enable image generation for this runner pool. When enabled, the runner pool is used to build and publish custom runner images.
       */
      image_gen?: boolean;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: actions_hosted_runner;
          };
        };
        examples: {
          default: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Deletes a GitHub-hosted runner for an organization.
 */
export type actionsDeleteHostedRunnerForOrg = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: actionsDeleteHostedRunnerForOrg_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      202: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: actions_hosted_runner;
          };
        };
        examples: {
          default: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type actionsGetHostedRunnerForOrg_Path = {
  org: string;
  hosted_runner_id: number;
};

export type actionsUpdateHostedRunnerForOrg_Path = {
  org: string;
  hosted_runner_id: number;
};

export type actionsDeleteHostedRunnerForOrg_Path = {
  org: string;
  hosted_runner_id: number;
};
