// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { minimal_repository } from "../../../../../../components/schemas/minimal-repository.js";
import type { requires_authentication } from "../../../../../../#/components/responses/requires_authentication.js";
import type { forbidden } from "../../../../../../#/components/responses/forbidden.js";
import type { not_found } from "../../../../../../#/components/responses/not_found.js";
import type { conflict } from "../../../../../../#/components/responses/conflict.js";
import type { internal_error } from "../../../../../../#/components/responses/internal_error.js";
import type { validation_failed } from "../../../../../../#/components/responses/validation_failed.js";

/**
 * > [!NOTE]
 * > This endpoint is in public preview and is subject to change.
 *
 * Lists the selected repositories that are enabled for Copilot cloud agent in an organization.
 *
 * Organization owners can use this endpoint when the coding agent repository policy
 * is set to `selected` to see which repositories have been enabled.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint.
 */
export type copilotListCopilotCodingAgentSelectedRepositoriesForOrganization = (
  $: OmitValueWhenNever<{
    query: copilotListCopilotCodingAgentSelectedRepositoriesForOrganization_Query;
    querystring: never;
    path: copilotListCopilotCodingAgentSelectedRepositoriesForOrganization_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              total_count: number;
              repositories: Array<minimal_repository>;
            };
          };
        };
        examples: {
          default: unknown;
        };
      };
      401: requires_authentication;
      403: forbidden;
      404: not_found;
      409: conflict;
      500: internal_error;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * > [!NOTE]
 * > This endpoint is in public preview and is subject to change.
 *
 * Replaces the list of selected repositories that are enabled for Copilot cloud
 * agent in an organization. This method can only be called when the cloud agent
 * repository policy is set to `selected`.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint.
 */
export type copilotSetCopilotCodingAgentSelectedRepositoriesForOrganization = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: copilotSetCopilotCodingAgentSelectedRepositoriesForOrganization_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * List of repository IDs to enable for Copilot cloud agent.
       */
      selected_repository_ids: Array<number>;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      401: requires_authentication;
      403: forbidden;
      404: not_found;
      409: conflict;
      422: validation_failed;
      500: internal_error;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type copilotListCopilotCodingAgentSelectedRepositoriesForOrganization_Query =
  { per_page?: number; page?: number };

export type copilotListCopilotCodingAgentSelectedRepositoriesForOrganization_Path =
  { org: string };

export type copilotSetCopilotCodingAgentSelectedRepositoriesForOrganization_Path =
  { org: string };
