// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../counterfact-types/index.ts";
import type { runner_groups_org } from "../../../../components/schemas/runner-groups-org.js";

/**
 * Lists all self-hosted runner groups configured in an organization and inherited from an enterprise.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint.
 */
export type actionsListSelfHostedRunnerGroupsForOrg = (
  $: OmitValueWhenNever<{
    query: actionsListSelfHostedRunnerGroupsForOrg_Query;
    querystring: never;
    path: actionsListSelfHostedRunnerGroupsForOrg_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: {
              total_count: number;
              runner_groups: Array<runner_groups_org>;
            };
          };
        };
        examples: {
          default: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Creates a new self-hosted runner group for an organization.
 *
 * OAuth tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint.
 */
export type actionsCreateSelfHostedRunnerGroupForOrg = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: actionsCreateSelfHostedRunnerGroupForOrg_Path;
    headers: never;
    cookie: never;
    body: {
      /**
       * Name of the runner group.
       */
      name: string;
      /**
       * Visibility of a runner group. You can select all repositories, select individual repositories, or limit access to private repositories.
       * @default "all"
       */
      visibility?: "selected" | "all" | "private";
      /**
       * List of repository IDs that can access the runner group.
       */
      selected_repository_ids?: Array<number>;
      /**
       * List of runner IDs to add to the runner group.
       */
      runners?: Array<number>;
      /**
       * Whether the runner group can be used by `public` repositories.
       * @default false
       */
      allows_public_repositories?: boolean;
      /**
       * If `true`, the runner group will be restricted to running only the workflows specified in the `selected_workflows` array.
       * @default false
       */
      restricted_to_workflows?: boolean;
      /**
       * List of workflows the runner group should be allowed to run. This setting will be ignored unless `restricted_to_workflows` is set to `true`.
       */
      selected_workflows?: Array<string>;
      /**
       * The identifier of a hosted compute network configuration.
       */
      network_configuration_id?: string;
    };
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: runner_groups_org;
          };
        };
        examples: {
          default: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type actionsListSelfHostedRunnerGroupsForOrg_Query = {
  per_page?: number;
  page?: number;
  visible_to_repository?: string;
};

export type actionsListSelfHostedRunnerGroupsForOrg_Path = { org: string };

export type actionsCreateSelfHostedRunnerGroupForOrg_Path = { org: string };
