// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../counterfact-types/index.ts";
import type { Context } from "../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../counterfact-types/index.ts";
import type { user_marketplace_purchase } from "../../../components/schemas/user-marketplace-purchase.js";
import type { not_modified } from "../../../#/components/responses/not_modified.js";
import type { requires_authentication } from "../../../#/components/responses/requires_authentication.js";

/**
 * Lists the active subscriptions for the authenticated user.
 */
export type appsListSubscriptionsForAuthenticatedUserStubbed = (
  $: OmitValueWhenNever<{
    query: appsListSubscriptionsForAuthenticatedUserStubbed_Query;
    querystring: never;
    path: never;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<user_marketplace_purchase>;
          };
        };
        examples: {
          default: unknown;
        };
      };
      304: not_modified;
      401: requires_authentication;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type appsListSubscriptionsForAuthenticatedUserStubbed_Query = {
  per_page?: number;
  page?: number;
};
