// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../counterfact-types/index.ts";
import type { MetricGroupRep } from "../../../../../../components/schemas/MetricGroupRep.js";
import type { InvalidRequestErrorRep } from "../../../../../../components/schemas/InvalidRequestErrorRep.js";
import type { UnauthorizedErrorRep } from "../../../../../../components/schemas/UnauthorizedErrorRep.js";
import type { ForbiddenErrorRep } from "../../../../../../components/schemas/ForbiddenErrorRep.js";
import type { NotFoundErrorRep } from "../../../../../../components/schemas/NotFoundErrorRep.js";
import type { MethodNotAllowedErrorRep } from "../../../../../../components/schemas/MethodNotAllowedErrorRep.js";
import type { RateLimitedErrorRep } from "../../../../../../components/schemas/RateLimitedErrorRep.js";
import type { JSONPatch } from "../../../../../../components/schemas/JSONPatch.js";

/**
 * Get information for a single metric group from the specific project.
 *
 * ### Expanding the metric group response
 * LaunchDarkly supports two fields for expanding the "Get metric group" response. By default, these fields are **not** included in the response.
 *
 * To expand the response, append the `expand` query parameter and add a comma-separated list with either or both of the following fields:
 *
 * - `experiments` includes all experiments from the specific project that use the metric group
 * - `experimentCount` includes the number of experiments from the specific project that use the metric group
 *
 * For example, `expand=experiments` includes the `experiments` field in the response.
 *
 */
export type getMetricGroup = (
  $: OmitValueWhenNever<{
    query: getMetricGroup_Query;
    querystring: never;
    path: getMetricGroup_Path;
    headers: getMetricGroup_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: MetricGroupRep;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InvalidRequestErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      405: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: MethodNotAllowedErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Patch a metric group by key. Updating a metric group uses a [JSON patch](https://datatracker.ietf.org/doc/html/rfc6902) representation of the desired changes.
 */
export type patchMetricGroup = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: patchMetricGroup_Path;
    headers: patchMetricGroup_Headers;
    cookie: never;
    body: JSONPatch;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: MetricGroupRep;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InvalidRequestErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      405: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: MethodNotAllowedErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

/**
 * Delete a metric group by key.
 */
export type deleteMetricGroup = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: deleteMetricGroup_Path;
    headers: deleteMetricGroup_Headers;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: never;
        requiredHeaders: never;
        content: never;
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InvalidRequestErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      405: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: MethodNotAllowedErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type getMetricGroup_Query = {
  /**
   * A comma-separated list of properties that can reveal additional information in the response.
   */
  expand?: string;
};

export type getMetricGroup_Path = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The metric group key
   */
  metricGroupKey: string;
};

export type getMetricGroup_Headers = { Authorization: string };

export type patchMetricGroup_Path = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The metric group key
   */
  metricGroupKey: string;
};

export type patchMetricGroup_Headers = { Authorization: string };

export type deleteMetricGroup_Path = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The metric group key
   */
  metricGroupKey: string;
};

export type deleteMetricGroup_Headers = { Authorization: string };
