// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../counterfact-types/index.ts";
import type { Context } from "../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../counterfact-types/index.ts";
import type { base_gist } from "../../../components/schemas/base-gist.js";
import type { validation_failed } from "../../../#/components/responses/validation_failed.js";

/**
 * Lists public gists for the specified user:
 */
export type gistsListForUser = (
  $: OmitValueWhenNever<{
    query: gistsListForUser_Query;
    querystring: never;
    path: gistsListForUser_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          Link: { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Array<base_gist>;
          };
        };
        examples: {
          default: unknown;
        };
      };
      422: validation_failed;
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type gistsListForUser_Query = {
  since?: string;
  per_page?: number;
  page?: number;
};

export type gistsListForUser_Path = { username: string };
