// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../../../counterfact-types/index.ts";
import type { IntegrationDeliveryConfigurationPost } from "../../../../../../../components/schemas/IntegrationDeliveryConfigurationPost.js";
import type { BigSegmentStoreIntegration } from "../../../../../../../components/schemas/BigSegmentStoreIntegration.js";
import type { InvalidRequestErrorRep } from "../../../../../../../components/schemas/InvalidRequestErrorRep.js";
import type { UnauthorizedErrorRep } from "../../../../../../../components/schemas/UnauthorizedErrorRep.js";
import type { ForbiddenErrorRep } from "../../../../../../../components/schemas/ForbiddenErrorRep.js";
import type { NotFoundErrorRep } from "../../../../../../../components/schemas/NotFoundErrorRep.js";
import type { StatusConflictErrorRep } from "../../../../../../../components/schemas/StatusConflictErrorRep.js";
import type { RateLimitedErrorRep } from "../../../../../../../components/schemas/RateLimitedErrorRep.js";

/**
 *
 * Create a persistent store integration.
 *
 * If you are using server-side SDKs, segments synced from external tools and larger list-based segments require a persistent store within your infrastructure. LaunchDarkly keeps the persistent store up to date and consults it during flag evaluation.
 *
 * You can use either Redis or DynamoDB as your persistent store. When you create a persistent store integration, the fields in the `config` object in the request vary depending on which persistent store you use.
 *
 * If you are using Redis to create your persistent store integration, you will need to know:
 *
 * * Your Redis host
 * * Your Redis port
 * * Your Redis username
 * * Your Redis password
 * * Whether or not LaunchDarkly should connect using TLS
 *
 * If you are using DynamoDB to create your persistent store integration, you will need to know:
 *
 * * Your DynamoDB table name. The table must have the following schema:
 *   * Partition key: `namespace` (string)
 *   * Sort key: `key` (string)
 * * Your DynamoDB Amazon Web Services (AWS) region.
 * * Your AWS role Amazon Resource Name (ARN). This is the role that LaunchDarkly will assume to manage your DynamoDB table.
 * * The External ID you specified when creating your Amazon Resource Name (ARN).
 *
 * To learn more, read [Segment configuration](https://docs.launchdarkly.com/home/flags/segment-config).
 *
 */
export type createBigSegmentStoreIntegration = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: createBigSegmentStoreIntegration_Path;
    headers: createBigSegmentStoreIntegration_Headers;
    cookie: never;
    body: IntegrationDeliveryConfigurationPost;
    context: Context;
    response: ResponseBuilderFactory<{
      201: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: BigSegmentStoreIntegration;
          };
        };
        examples: {};
      };
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: InvalidRequestErrorRep;
          };
        };
        examples: {};
      };
      401: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UnauthorizedErrorRep;
          };
        };
        examples: {};
      };
      403: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ForbiddenErrorRep;
          };
        };
        examples: {};
      };
      404: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: NotFoundErrorRep;
          };
        };
        examples: {};
      };
      409: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: StatusConflictErrorRep;
          };
        };
        examples: {};
      };
      429: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: RateLimitedErrorRep;
          };
        };
        examples: {};
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    auth: { apiKey: string };
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type createBigSegmentStoreIntegration_Path = {
  /**
   * The project key
   */
  projectKey: string;
  /**
   * The environment key
   */
  environmentKey: string;
  /**
   * The integration key, either `redis` or `dynamodb`
   */
  integrationKey: string;
};

export type createBigSegmentStoreIntegration_Headers = {
  Authorization: string;
};
