// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq.md

import type { WideOperationArgument } from "../../../../../../counterfact-types/index.ts";
import type { OmitValueWhenNever } from "../../../../../../counterfact-types/index.ts";
import type { MaybePromise } from "../../../../../../counterfact-types/index.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../counterfact-types/index.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../counterfact-types/index.ts";
import type { code_security_default_configurations } from "../../../../../components/schemas/code-security-default-configurations.js";

/**
 * Lists the default code security configurations for an enterprise.
 *
 * The authenticated user must be an administrator of the enterprise in order to use this endpoint.
 *
 * OAuth app tokens and personal access tokens (classic) need the `read:enterprise` scope to use this endpoint.
 */
export type codeSecurityGetDefaultConfigurationsForEnterprise = (
  $: OmitValueWhenNever<{
    query: never;
    querystring: never;
    path: codeSecurityGetDefaultConfigurationsForEnterprise_Path;
    headers: never;
    cookie: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: code_security_default_configurations;
          };
        };
        examples: {
          default: unknown;
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
    delay: (milliseconds: number, maxMilliseconds?: number) => Promise<void>;
    version: never;
  }>,
) => MaybePromise<COUNTERFACT_RESPONSE>;

export type codeSecurityGetDefaultConfigurationsForEnterprise_Path = {
  enterprise: string;
};
